ValueSet: DCGeneralServiceTypeMultipleChoiceSampleCollectionTestingTreatmentFollowUPVS
Title: "DC-General-Service Type-Multiple Choice-Sample Collection/Testing/Treatment/Follow UP value set"
* codes from system DCGeneralServiceTypeMultipleChoiceSampleCollectionTestingTreatmentFollowUPCS
