ValueSet: DCMalariaLabMicroscopyResultSpeciesAllFiveSpeciesVivaxFalciparumOvaleMalariaeKnowlesiMixedVS
Title: "DC-Malaria-Lab  Microscopy Result Species- all five species vivax/falciparum/ovale/malariae/knowlesi/Mixed value set"
* codes from system DCMalariaLabMicroscopyResultSpeciesAllFiveSpeciesVivaxFalciparumOvaleMalariaeKnowlesiMixedCS
