ValueSet: IMAMMedicalHistoryDecisionAdmissionTypeNewReadmissionDefaulterTransferInVS
Title: "IMAM-Medical History-Decision-Admission Type-new/Readmission/defaulter/transfer in value set"
* codes from system IMAMMedicalHistoryDecisionAdmissionTypeNewReadmissionDefaulterTransferInCS
