ValueSet: IMCIDiarrhoeaDehydrationClassificationSevereDehydrationSomeDehydrationNoDehydrationVS
Title: "IMCI-Diarrhoea-Dehydration-classification-Severe dehydration/Some dehydration/no dehydration value set"
* codes from system IMCIDiarrhoeaDehydrationClassificationSevereDehydrationSomeDehydrationNoDehydrationCS
