ValueSet: IMCINutritionUnderweightClassificationSevereUnderweightModerateUnderweightNoUnderweightVS
Title: "IMCI-Nutrition-Underweight classification-Severe underweight/Moderate underweight/No underweight value set"
* codes from system IMCINutritionUnderweightClassificationSevereUnderweightModerateUnderweightNoUnderweightCS
