ValueSet: IMCIExaminationDiarrhoeaGeneralConditionRestlessIrritableLethargicUnconsciousVS
Id: imci-examination-diarrhoea-general-condition
Title: "IMCI-Examination-Diarrhoea-General Condition-restless/irritable Lethargic/unconscious value set"
* codes from system IMCIExaminationDiarrhoeaGeneralConditionRestlessIrritableLethargicUnconsciousCS
