ValueSet: IMCIFeverMalariaEndemicDistrictFourClassificationsSevereFalciparumMalariaNoMalariaVS
Title: "IMCI-Fever-malaria endemic district-four classifications-severe/falciparum/malaria/no malaria value set"
* codes from system IMCIFeverMalariaEndemicDistrictFourClassificationsSevereFalciparumMalariaNoMalariaCS
