ValueSet: IMCIClassificationNutritionSevereAcuteMalnutritionModerateAcuteMalnutritionNoAcuteMalnutritionVS
Title: "IMCI-Classification-Nutrition-Severe Acute malnutrition/Moderate Acute malnutrition/No Acute malnutrition value set"
* codes from system IMCIClassificationNutritionSevereAcuteMalnutritionModerateAcuteMalnutritionNoAcuteMalnutritionCS
