ValueSet: RHMorbidityFistulaScreeningDiagnosisResultNormalSuspectedFistulaVS
Title: "RH Morbidity-Fistula-Screening-Diagnosis-Result Normal/Suspected Fistula value set"
* codes from system RHMorbidityFistulaScreeningDiagnosisResultNormalSuspectedFistulaCS
