ValueSet: SASFollowUpOutcomeCompleteIncompleteOngoingPregnancyEctopicPregnancyVS
Title: "SAS-Follow Up-Outcome-Complete/Incomplete/Ongoing pregnancy/Ectopic Pregnancy value set"
* codes from system SASFollowUpOutcomeCompleteIncompleteOngoingPregnancyEctopicPregnancyCS
