CodeSystem: CODCauseCommunicableDiseaseAllCS
Title: "COD-Cause-Communicable Disease-All"
* #"1" "Tuberculosis"
* #"2" "Malaria"
* #"3" "Kala-Azar"
* #"4" "HIV-AIDS"
* #"5" "Dengue"
* #"6" "Japanease Encephalitis"
* #"7" "Leprosy"
* #"8" "Typhoid"
* #"9" "Other"
