CodeSystem: ICDSMPANCSCS
Title: "ICD_SMP_ANCS"
* #"JA01" "JA01 Ectopic pregnancy"
* #"JA05" "JA05 Complications following abortion, ectopic or molar pregnancy"
* #"JA24" "JA24 Pre-eclampsia"
* #"JA25" "JA25 Eclampsia"
* #"JA41" "JA41 Antepartum haemorrhage"
* #"JA60.0" "JA60.0 Mild hyperemesis gravidarum"
* #"JA23" "Gestational Hypertension"
* #"1" "Other Complication"
