CodeSystem: ICDSMPDeliveriesCS
Title: "ICD_SMP_Deliveries"
* #"JA24" "JA24 Pre-eclampsia"
* #"JA25" "JA25 Eclampsia"
* #"JB03" "JB03 Long labour"
* #"JB06" "JB06 Obstructed labour due to other causes"
* #"JB0A.1" "JB0A.1 Rupture of uterus during labour"
* #"JA41" "JA41 Antepartum haemorrhage"
* #"JA42" "JA42 Intrapartum Haemorrhage"
* #"JA43" "JA43 Postpartum haemorrhage"
* #"JB0B.0" "JB0B.0 Retained Placenta"
* #"JB0Y" "JB0Y Other specified complications of labour or delivery"
