CodeSystem: ICDSmolCS
Title: "ICD-SMoL"
* #"5-1" "Cholera"
* #"5-2" "Typhoid and paratyphoid"
* #"5-3" "Other and unspecified diarrhoeal diseases"
* #"5-4" "Tuberculosis"
* #"5-4.1" "Respiratory tuberculosis, confirmed bacteriologically or histologically"
* #"5-4.9" "Other tuberculosis"
* #"5-5" "Plague"
* #"5-6" "Leprosy"
* #"5-7" "Tetanus"
* #"5-8" "Diphtheria"
* #"5-9" "Whooping cough"
* #"5-10" "Meningococcal infection"
* #"5-11" "Septicaemia"
* #"5-12" "Infections with a predominantly sexual mode of transmission"
* #"5-12.1" "Syphilis"
* #"5-12.9" "Other and unspecified infections with a predominantly sexual mode of transmission"
* #"5-13" "Acute poliomyelitis"
* #"5-14" "Rabies"
* #"5-15" "Dengue"
* #"5-16" "Yellow fever"
* #"5-17" "Other viral haemorrhagic fevers"
* #"5-18" "Measles"
* #"5-19" "Viral hepatitis"
* #"5-19.1" "Hepatitis B"
* #"5-19.8" "Other viral hepatitis"
* #"5-19.9" "Unspecified viral hepatitis"
* #"5-20" "Human immunodeficiency virus [HIV] disease"
* #"5-20.1" "HIV disease with tuberculosis"
* #"5-20.2" "Other and unspecified HIV disease"
* #"5-21" "Malaria"
* #"5-21.1" "Malaria, parasitologically confirmed"
* #"5-21.9" "Other and unspecified malaria"
* #"5-22" "Leishmaniasis"
* #"5-23" "Trypanosomiasis"
* #"5-24" "Schistosomiasis"
* #"5-25" "Other and unspecified infectious diseases"
* #"5-26" "Malignant neoplasm of lip, oral cavity and pharynx"
* #"5-27" "Malignant neoplasm of Oesophagus"
* #"5-28" "Malignant neoplasm of stomach"
* #"5-29" "Malignant neoplasm of colon, rectum and anus"
* #"5-30" "Malignant neoplasm of liver and intrahepatic bile ducts"
* #"5-31" "Malignant neoplasm of pancreas"
* #"5-32" "Malignant neoplasm of larynx"
* #"5-33" "Malignant neoplasm of trachea, bronchus and lung"
* #"5-34" "Malignant melanoma of skin"
* #"5-35" "Malignant neoplasm of breast"
* #"5-36" "Malignant neoplasm of cervix uteri"
* #"5-37" "Malignant neoplasm of other and unspecified parts of uterus"
* #"5-38" "Malignant neoplasm of ovary"
* #"5-39" "Malignant neoplasm of prostate"
* #"5-40" "Malignant neoplasm of bladder"
* #"5-41" "Malignant neoplasm of meninges, brain and other parts of central nervous system"
* #"5-42" "Non-Hodgkin lymphoma"
* #"5-43" "Multiple myeloma and malignant plasma cell neoplasms"
* #"5-44" "Leukaemia"
* #"5-45" "Other and unspecified malignant neoplasms"
* #"5-46" "Benign neoplasms"
* #"5-47" "Anaemias"
* #"5-48" "Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
* #"5-49" "Diabetes mellitus"
* #"5-50" "Protein-energy malnutrition"
* #"5-51" "Other and unspecified endocrine, nutritional and metabolic diseases"
* #"5-52" "Alcohol use disorders"
* #"5-53" "Drug use disorders"
* #"5-54" "Other mental and behavioural disorders"
* #"5-55" "Meningitis"
* #"5-56" "Alzheimer's disease, dementias"
* #"5-57" "Other diseases of the nervous system"
* #"5-58" "Diseases of the eye and adnexa"
* #"5-59" "Diseases of the ear and mastoid process"
* #"5-60" "Acute rheumatic fever and chronic rheumatic heart diseases"
* #"5-61" "Hypertensive heart diseases"
* #"5-62" "Ischaemic heart diseases"
* #"5-63" "Other heart diseases"
* #"5-64" "Cerebrovascular diseases"
* #"5-65" "Other and unspecified diseases of the circulatory system"
* #"5-66" "Influenza"
* #"5-67" "Pneumonia"
* #"5-68" "Other acute lower respiratory infections"
* #"5-69" "Chronic lower respiratory diseases"
* #"5-70" "Other and unspecified diseases of the respiratory system"
* #"5-71" "Gastric and duodenal ulcer"
* #"5-72" "Appendicitis"
* #"5-73" "Liver cirrhosis"
* #"5-74" "Other diseases of the digestive system"
* #"5-75" "Diseases of the skin and subcutaneous tissue"
* #"5-76" "Diseases of the musculoskeletal system and connective tissue"
* #"5-77" "Glomerular and renal tubulo-interstitial diseases"
* #"5-78" "Other and unspecified diseases of the genitourinary system"
* #"5-79" "Pregnancy with abortive outcome"
* #"5-80" "Maternal hypertensive disorders"
* #"5-81" "Obstructed labour"
* #"5-82" "Maternal haemorrhage"
* #"5-83" "Maternal sepsis"
* #"5-84" "Other direct obstetric deaths"
* #"5-85" "Indirect obstetric deaths"
* #"5-86" "Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery"
* #"5-87" "Disorders relating to length of gestation and foetal growth"
* #"5-87.1" "Prematurity"
* #"5-87.2" "Low birth weight"
* #"5-87.9" "Other and unspecified disorders relating to length of gestation and fetal growth"
* #"5-88" "Birth trauma"
* #"5-89" "Intrauterine hypoxia and birth asphyxia"
* #"5-201" "Sepsis and other infectious conditions of the newborn"
* #"5-90" "Other and unspecified perinatal conditions"
* #"5-91" "Congenital hydrocephalus and spina bifida"
* #"5-92" "Congenital malformations of the heart"
* #"5-93" "Down syndrome and other chromosomal abnormalities"
* #"5-94" "Other and unspecified congenital malformations"
* #"5-95" "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified"
* #"5-96" "Road traffic accidents"
* #"5-97" "Other transport accidents"
* #"5-98" "Falls"
* #"5-99" "Accidental drowning and submersion"
* #"5-100" "Exposure to smoke, fire and flames"
* #"5-101" "Exposure to forces of nature"
* #"5-102" "Accidental poisoning by and exposure to noxious substances"
* #"5-102.1" "Alcohol poisoning"
* #"5-102.2" "Drug poisoning"
* #"5-102.3" "Food poisoning"
* #"5-102.9" "Other and unspecified poisoning"
* #"5-103" "Intentional self-harm"
* #"5-104" "Assault"
* #"5-105" "Conflict and war"
* #"5-106" "Other and unspecified external causes"
