CodeSystem: ICDSMPPNCCS
Title: "ICD_SMP_PNC"
* #"JA24" "JA24 Pre-eclampsia"
* #"JA25" "JA25 Eclampsia"
* #"JA43" "JA43 Postpartum haemorrhage"
* #"JA43.0" "JA43.0 Third-stage haemorrhage"
* #"JB40.0" "JB40.0 Puerperal sepsis"
* #"JB40.1" "JB40.1 Infection of obstetric surgical wound"
* #"JA23" "JA23 Gestational Hypertension"
* #"JB0Y" "JB0Y Other specified complications of labour or delivery"
