CodeSystem: MannerOfDeathCS
Title: "Manner of death"
* #"ACCIDENT" "Accident"
* #"ASSAULT" "Assault"
* #"NOT_DETERMINED" "Could not be determined"
* #"DISEASE" "Disease"
* #"SUICIDE" "Intentional self-harm"
* #"LEGAL_INTERVENTION" "Legal intervention"
* #"PENDING_INVESTIGATION" "Pending investigation"
* #"UNKNOWN" "Unknown"
* #"WAR" "War"
