CodeSystem: OPDESSENTIALMEDICINESCS
Title: "OPD ESSENTIAL MEDICINES"
* #"Capsule_Activated_Charcoal_250mg" "Capsule Activated Charcoal 250mg"
* #"Capsule_Amoxycillin_500mg" "Capsule Amoxycillin 500mg"
* #"Capsule_Amoxycillin__Clavulanic_acid_250mg_125mg" "Capsule Amoxycillin+ Clavulanic acid 250mg+125mg"
* #"Capsule_Amoxycillin_Cloxacillin_125mg_125mg" "Capsule Amoxycillin+Cloxacillin 125mg+125mg"
* #"Capsule_Amoxycillin_Cloxacillin_500mg_500mg" "Capsule Amoxycillin+Cloxacillin 500mg+500mg"
* #"Capsule_Beclomethasone_Rotacap_200Mcg" "Capsule Beclomethasone Rotacap 200Mcg"
* #"Capsule_Beclomethasone_Rotacap_400mcg" "Capsule Beclomethasone Rotacap 400mcg"
* #"Capsule_Bifilac_" "Capsule Bifilac"
* #"Capsule_Budesonide_Inhaler_100mcg" "Capsule Budesonide Inhaler 100mcg"
* #"Capsule_Budesonide_Inhaler_200Mcg" "Capsule Budesonide Inhaler 200Mcg"
* #"Capsule_Budesonide_Rotacap_100mcg" "Capsule Budesonide Rotacap 100mcg"
* #"Capsule_Budesonide_Rotacap_200mcg" "Capsule Budesonide Rotacap 200mcg"
* #"Capsule_Budesonide_Rotacap_400mcg" "Capsule Budesonide Rotacap 400mcg"
* #"Capsule_Clavam_625mg" "Capsule Clavam 625mg"
* #"Capsule_Clindamycin_300mg" "Capsule Clindamycin 300mg"
* #"Capsule_Digestive_enzyme_(Pepsin_Diatase)_10mg_50m" "Capsule Digestive enzyme (Pepsin+Diatase) 10mg+50mg"
* #"Capsule_Doxycycline_50mg" "Capsule Doxycycline 50mg"
* #"Capsule_Doxycycline_100mg" "Capsule Doxycycline 100mg"
* #"Capsule_Doxycycline_100mg*2cap" "Capsule Doxycycline 100mg*2cap"
* #"Capsule_Flucloxacillin_250mg" "Capsule Flucloxacillin 250mg"
* #"Capsule_Flucloxacillin_500mg" "Capsule Flucloxacillin 500mg"
* #"Capsule_Fluconazole_50mg" "Capsule Fluconazole 50mg"
* #"Capsule_Fluconazole_100mg" "Capsule Fluconazole 100mg"
* #"Capsule_Fluconazole_150mg" "Capsule Fluconazole 150mg"
* #"Capsule_Fluoxetine_10mg" "Capsule Fluoxetine 10mg"
* #"Capsule_Fluoxetine_20" "Capsule Fluoxetine 20"
* #"Capsule_Foracort_400mcg" "Capsule Foracort 400mcg"
* #"Capsule_Formoterol_fumarate_and_budesonide_200mcg" "Capsule Formoterol fumarate and budesonide 200mcg"
* #"Capsule_Formoterol_fumarate_and_budesonide_400mcg" "Capsule Formoterol fumarate and budesonide 400mcg"
* #"Capsule_Indomethacine_25mg" "Capsule Indomethacine 25mg"
* #"Capsule_Indomethacine_50mg" "Capsule Indomethacine 50mg"
* #"Capsule_Nifedipine_10mg" "Capsule Nifedipine 10mg"
* #"Capsule_Omeprazole_20mg" "Capsule Omeprazole 20mg"
* #"Capsule_Pantoprazole__Domperidone_40mg_30mg" "Capsule Pantoprazole+ Domperidone 40mg+30mg"
* #"Capsule_Periclox_500mg" "Capsule Periclox 500mg"
* #"Capsule_SALMETEROL_FLUTICASONE_250mcg" "Capsule SALMETEROL+FLUTICASONE 250mcg"
* #"Capsule_Tiotropium_bromide_18mcg" "Capsule Tiotropium bromide 18mcg"
* #"Capsule_Tiova_18mcg" "Capsule Tiova 18mcg"
* #"Capsule_Tiova_rotacap_(Tiotropium)_18mcg" "Capsule Tiova rotacap (Tiotropium) 18mcg"
* #"Capsule_Vitamin_A_(Retinol)_2,00,000IU" "Capsule Vitamin A (Retinol) 2,00,000IU"
* #"Capsule_Vitamin_A_(Retinol)_50,000IU" "Capsule Vitamin A (Retinol) 50,000IU"
* #"Cream_Acyclovir_0.03" "Cream Acyclovir 0.03"
* #"Cream_Acyclovir_0.05" "Cream Acyclovir 0.05"
* #"Cream_Butenafine_0.01" "Cream Butenafine 0.01"
* #"Cream_Chlorhexidine_0.002" "Cream Chlorhexidine 0.002"
* #"Cream_Cosmelite_g_" "Cream Cosmelite-g"
* #"Cream_Fungigard_(Miconazole)_0.02" "Cream Fungigard (Miconazole) 0.02"
* #"Cream_Fusidic_acid_0.02" "Cream Fusidic acid 0.02"
* #"Cream_Hydrocortisone_acetate_1.0%w_w" "Cream Hydrocortisone acetate 1.0%w/w"
* #"Cream_Hydroquinone_0.02" "Cream Hydroquinone 0.02"
* #"Cream_Neomycin_0.02" "Cream Neomycin 0.02"
* #"Cream_Neomycin_Sulphate__Clobetasol_propionate_0.5" "Cream Neomycin Sulphate+ Clobetasol propionate 0.5%+0.05%"
* #"Cream_Permethrin_0.05" "Cream Permethrin 0.05"
* #"Cream_Silver_Nitrate__Chlorhexidine_0.2%_0.2%" "Cream Silver Nitrate+ Chlorhexidine 0.2%+0.2%"
* #"Cream_Sonaderm_GM_" "Cream Sonaderm-GM"
* #"Drop_Amoxycillin_100mg_ml" "Drop Amoxycillin 100mg/ml"
* #"Drop_Ampicillin_Cloxacillin_60mg_30mg" "Drop Ampicillin+Cloxacillin 60mg+30mg"
* #"Drop_Atropine_0.01" "Drop Atropine 0.01"
* #"Drop_Betamethasone0.1%___Neomycin_Eye_Drops_" "Drop Betamethasone0.1% + Neomycin Eye Drops"
* #"Drop_candid_ear_drop_" "Drop candid ear drop"
* #"Drop_Carboxymethylcellulose_eye_drop_0.005" "Drop Carboxymethylcellulose eye drop 0.005"
* #"Drop_Cetaphenicol_and_benzocaine_ear_drop_5%_1%%" "Drop Cetaphenicol and benzocaine ear drop 5%+1%%"
* #"Drop_Chloramphenicol_eye_drop_0.5%w_v" "Drop Chloramphenicol eye drop 0.5%w/v"
* #"Drop_Ciprofloxacin_e_e_drop_0.003" "Drop Ciprofloxacin e/e drop 0.003"
* #"Drop_Clove_oil_5ml" "Drop Clove oil 5ml"
* #"Drop_Fluconazole_0.003" "Drop Fluconazole 0.003"
* #"Drop_Fluorometholone_eye_drop_0.001" "Drop Fluorometholone eye drop 0.001"
* #"Drop_Fluorometholone__Neomycin_eye_drop_0.1%_0.5%" "Drop Fluorometholone+ Neomycin eye drop 0.1%+0.5%"
* #"Drop_Flurbiprofen_eye_drop_0.0003" "Drop Flurbiprofen eye drop 0.0003"
* #"Drop_Gentamycin_0.003" "Drop Gentamycin 0.003"
* #"Drop_Glycerin_ear_drop_" "Drop Glycerin ear drop"
* #"Drop_Hydroxymethylcellulose_0.02" "Drop Hydroxymethylcellulose 0.02"
* #"Drop_Ketorolac_tromethamine_eye_drop_0.004" "Drop Ketorolac tromethamine eye drop 0.004"
* #"Drop_Lubrica__Carboxymethyl_cellulose_5mg_ml" "Drop Lubrica- Carboxymethyl cellulose 5mg/ml"
* #"Drop_Ofloxacin_1drop" "Drop Ofloxacin 1drop"
* #"Drop_Olopatadine_1drop" "Drop Olopatadine 1drop"
* #"Drop_Olopatadine_eye_drop_0.002" "Drop Olopatadine eye drop 0.002"
* #"Drop_Oxymetazoline_0.0003" "Drop Oxymetazoline 0.0003"
* #"Drop_Oxymetazoline_0.0005" "Drop Oxymetazoline 0.0005"
* #"Drop_Oxymetazoline_0.00025" "Drop Oxymetazoline 0.00025"
* #"Drop_Prednisolone_" "Drop Prednisolone"
* #"Drop_Prednisolone_eye_drop_0.005" "Drop Prednisolone eye drop 0.005"
* #"Drop_Tobramycin_1drop" "Drop Tobramycin 1drop"
* #"Drop_Tobramycin_eye_drop_" "Drop Tobramycin eye drop"
* #"Gel_Adapalene___Clindamycin_" "Gel Adapalene + Clindamycin"
* #"Gel_D.F.O._Gel_" "Gel D.F.O. Gel"
* #"Gel_Delta_gel_10gm" "Gel Delta gel 10gm"
* #"Gel_Diclofenac_" "Gel Diclofenac"
* #"Gel_Diclofenac_(Ninja_Gel)_" "Gel Diclofenac (Ninja Gel)"
* #"Gel_Tricaine_MPS_" "Gel Tricaine MPS"
* #"Gel_Visco_10ml" "Gel Visco 10ml"
* #"Gel_Zytee_(Choline_salicylate_and_Benzalkonium)_9." "Gel Zytee (Choline salicylate and Benzalkonium) 9.0%+0.02%"
* #"Injection_Acetylcysteine_1gm_5ml" "Injection Acetylcysteine 1gm/5ml"
* #"Injection_Aciclovir_250mg_10ml" "Injection Aciclovir 250mg/10ml"
* #"Injection_Actinomycin_D_0.5mg_ml" "Injection Actinomycin D 0.5mg/ml"
* #"Injection_Adenosine_6mg_2ml" "Injection Adenosine 6mg/2ml"
* #"Injection_Adrenaline_1mg" "Injection Adrenaline 1mg"
* #"Injection_Alpha_Interferon_3MIU" "Injection Alpha Interferon 3MIU"
* #"Injection_Amikacin_100mg_Vial" "Injection Amikacin 100mg/Vial"
* #"Injection_Amikacin_200mg_vial" "Injection Amikacin 200mg/vial"
* #"Injection_Amikacin_500mg" "Injection Amikacin 500mg"
* #"Injection_Amino_acid_0.1" "Injection Amino acid 0.1"
* #"Injection_Amino_acid_0.05" "Injection Amino acid 0.05"
* #"Injection_Aminophyllin_250mg_10ml" "Injection Aminophyllin 250mg/10ml"
* #"Injection_Amiodarone_50mg_ml" "Injection Amiodarone 50mg/ml"
* #"Injection_Amoxycillin__Clavulanic_acid_1.2gm" "Injection Amoxycillin+ Clavulanic acid 1.2gm"
* #"Injection_Amphotericin_B_lyophilized_50mg" "Injection Amphotericin B lyophilized 50mg"
* #"Injection_Ampicillin_250mg_5ml" "Injection Ampicillin 250mg/5ml"
* #"Injection_Ampicillin_Cloxacillin_250mg_250mg" "Injection Ampicillin+Cloxacillin 250mg+250mg"
* #"Injection_Anti_rabies_vaccine_" "Injection Anti rabies vaccine"
* #"Injection_Anti_RhD_Immunoglobulin_300mcg" "Injection Anti RhD Immunoglobulin 300mcg"
* #"Injection_Anti_Venom_" "Injection Anti-Venom"
* #"Injection_Artesunate_60mg_amp" "Injection Artesunate 60mg/amp"
* #"Injection_Atropine_0.6mg" "Injection Atropine 0.6mg"
* #"Injection_Azithromycin_500mg" "Injection Azithromycin 500mg"
* #"Injection_Benzathine_Benzylpenicillin_1200000IU" "Injection Benzathine Benzylpenicillin 1200000IU"
* #"Injection_Calcium_gluconate_1g_10ml" "Injection Calcium gluconate 1g/10ml"
* #"Injection_Cefazolin_1gm" "Injection Cefazolin 1gm"
* #"Injection_Cefazoline_500mg" "Injection Cefazoline 500mg"
* #"Injection_Cefotaxime_1gm" "Injection Cefotaxime 1gm"
* #"Injection_Cefotaxime_500mg" "Injection Cefotaxime 500mg"
* #"Injection_Ceftazidime_1gm" "Injection Ceftazidime 1gm"
* #"Injection_Ceftriaxone_1gm" "Injection Ceftriaxone 1gm"
* #"Injection_Ceftriaxone_250mg" "Injection Ceftriaxone 250mg"
* #"Injection_Ceftriaxone_500mg" "Injection Ceftriaxone 500mg"
* #"Injection_Cefuroxime_1.5gm" "Injection Cefuroxime 1.5gm"
* #"Injection_Cefuroxime_750mg" "Injection Cefuroxime 750mg"
* #"Injection_Cephalexin_500mg" "Injection Cephalexin 500mg"
* #"Injection_Ciprofloxacin_200mg_100ml" "Injection Ciprofloxacin 200mg/100ml"
* #"Injection_Clindamycin_300mg" "Injection Clindamycin 300mg"
* #"Injection_Clindamycin_600mg" "Injection Clindamycin 600mg"
* #"Injection_Dazepam_5mg_ml" "Injection Dazepam 5mg/ml"
* #"Injection_Depo__Medroxyprogesterone_acetate_150mg_" "Injection Depo- Medroxyprogesterone acetate 150mg/ml"
* #"Injection_Dexamethasone_4mg_ml" "Injection Dexamethasone 4mg/ml"
* #"Injection_Dexamethasone_8Mg_2ml" "Injection Dexamethasone 8Mg/2ml"
* #"Injection_Dextrose_0.1" "Injection Dextrose 0.1"
* #"Injection_Dextrose_0.5" "Injection Dextrose 0.5"
* #"Injection_Dextrose_0.05" "Injection Dextrose 0.05"
* #"Injection_Dextrose_0.25" "Injection Dextrose 0.25"
* #"Injection_Diazepam_5mg_ml" "Injection Diazepam 5mg/ml"
* #"Injection_Diclofenac_25mg_3ml" "Injection Diclofenac 25mg/3ml"
* #"Injection_Diclofenac_75mg_ml" "Injection Diclofenac 75mg/ml"
* #"Injection_Digoxin_0.5mg" "Injection Digoxin 0.5mg"
* #"Injection_Doxycycline_100mg_Vial" "Injection Doxycycline 100mg/Vial"
* #"Injection_Esmoprazole_40mg_vial" "Injection Esmoprazole 40mg/vial"
* #"Injection_Flucloxacillin_500mg_vial" "Injection Flucloxacillin 500mg/vial"
* #"Injection_Fluorouracil_250mg_5ml" "Injection Fluorouracil 250mg/5ml"
* #"Injection_Fluorouracil_500mg_5ml" "Injection Fluorouracil 500mg/5ml"
* #"Injection_Frusemide_10mg_ml" "Injection Frusemide 10mg/ml"
* #"Injection_Frusemide_20mg" "Injection Frusemide 20mg"
* #"Injection_Gentamycin_40mg_ml" "Injection Gentamycin 40mg/ml"
* #"Injection_Haloperidol_5mg_ml" "Injection Haloperidol 5mg/ml"
* #"Injection_Heparin_25000IU_5ml" "Injection Heparin 25000IU/5ml"
* #"Injection_Hepatitis_A_(Adult)_vaccine_" "Injection Hepatitis A (Adult) vaccine"
* #"Injection_Hydrocortisone_100mg_Vial" "Injection Hydrocortisone 100mg/Vial"
* #"Injection_Hyoscine_butylbromide_20mg" "Injection Hyoscine butylbromide 20mg"
* #"Injection_Hyoscine_butylbromide_20Mg_ml" "Injection Hyoscine butylbromide 20Mg/ml"
* #"Injection_Implant_levonorgestrel__5_years_effectiv" "Injection Implant levonorgestrel- 5 years effectiveness 75mg/rod"
* #"Injection_Inj_.t.t._0.5ml" "Injection Inj .t.t. 0.5ml"
* #"Injection_Inj.pheneramine_4mg" "Injection Inj.pheneramine 4mg"
* #"Injection_Insulin_30_70_100IU_1ml" "Injection Insulin 30/70 100IU/1ml"
* #"Injection_Insulin_50_50_100IU_1ml" "Injection Insulin 50/50 100IU/1ml"
* #"Injection_Insulin,_regular_(NPH)_40IU_ml" "Injection Insulin, regular (NPH) 40IU/ml"
* #"Injection_Ketoralac_tromethamine_30mg" "Injection Ketoralac tromethamine 30mg"
* #"Injection_Magnesium_sulphate_500mg" "Injection Magnesium sulphate 500mg"
* #"Injection_Medroxyprogesterone_Acetate_150mg" "Injection Medroxyprogesterone Acetate 150mg"
* #"Injection_Metoclopramide_5mg_5ml" "Injection Metoclopramide 5mg/5ml"
* #"Injection_Metoclopramide_10mg" "Injection Metoclopramide 10mg"
* #"Injection_Metronidazole_500mg_100ml" "Injection Metronidazole 500mg/100ml"
* #"Injection_Oxytocin_10IU_ml" "Injection Oxytocin 10IU/ml"
* #"Injection_Paracetamol_1g_100ml" "Injection Paracetamol 1g/100ml"
* #"Injection_Paracetamol_150mg_2ml" "Injection Paracetamol 150mg/2ml"
* #"Injection_Pheniramine_22.75mg_ml" "Injection Pheniramine 22.75mg/ml"
* #"Injection_Pralidoxin_sodium_500mg,20ml" "Injection Pralidoxin sodium 500mg,20ml"
* #"Injection_Pyridoxine_10mg" "Injection Pyridoxine 10mg"
* #"Injection_Ranitidine_25Mg_ml" "Injection Ranitidine 25Mg/ml"
* #"Injection_Ranitidine_50mg" "Injection Ranitidine 50mg"
* #"Injection_Salbutamol_0.5mg_ml" "Injection Salbutamol 0.5mg/ml"
* #"Injection_Sodium_valporate_100mg_5ml" "Injection Sodium valporate 100mg/5ml"
* #"Injection_Tetanus_toxoid_(TT)_0.5ml" "Injection Tetanus toxoid (TT) 0.5ml"
* #"Injection_Tramadol_HCl_50mg" "Injection Tramadol HCl 50mg"
* #"Injection_Tranexamic_acid_500mg" "Injection Tranexamic acid 500mg"
* #"Injection_Typhoid_Vaccine_0.5ml" "Injection Typhoid Vaccine 0.5ml"
* #"Injection_Vitamin_K_10mg_ml" "Injection Vitamin K 10mg/ml"
* #"Liquid_Carmicide_5ml" "Liquid Carmicide 5ml"
* #"Liquid_Gentian_violet_(GV)_0.01" "Liquid Gentian violet (GV) 0.01"
* #"Liquid_Glycerin_enema_0.8" "Liquid Glycerin enema 0.8"
* #"Liquid_Nowax_3_4drop" "Liquid Nowax 3-4drop"
* #"Liquid_Oximetazoline_nasal_drop_0.0005" "Liquid Oximetazoline nasal drop 0.0005"
* #"Liquid_Prithimin_lotion_0.05" "Liquid Prithimin lotion 0.05"
* #"Liquid_Vasodryl_5ml" "Liquid Vasodryl 5ml"
* #"Lotion_Calamine_0.15" "Lotion Calamine 0.15"
* #"Lotion_Fluconazole_" "Lotion Fluconazole"
* #"Lotion_Gamma_benzene_hexachloride_0.01" "Lotion Gamma benzene hexachloride 0.01"
* #"Lotion_Ketoconazole_soap_0.01" "Lotion Ketoconazole soap 0.01"
* #"Lotion_Lactulose_3.35Gram(200ml)" "Lotion Lactulose 3.35Gram(200ml)"
* #"Lotion_Permethrin_0.05" "Lotion Permethrin 0.05"
* #"Lotion_Scabies_lotion_(Permethrin)_0.05" "Lotion Scabies lotion (Permethrin) 0.05"
* #"Lotion_Scabur_(Benzyl_Benzoate)_" "Lotion Scabur (Benzyl Benzoate)"
* #"Lotion_Sliver_sulfadiazine_20gm" "Lotion Sliver sulfadiazine 20gm"
* #"Ointment_Anti_Haemorrhoidal_" "Ointment Anti Haemorrhoidal"
* #"Ointment_Benzoic_and_Salicylic_acid_6%&amp;3%" "Ointment Benzoic and Salicylic acid 6%&3%"
* #"Ointment_Betamethasone_0.001" "Ointment Betamethasone 0.001"
* #"Ointment_Betamethasone_0.1%w_v___Neomycin_0.5%w_v_" "Ointment Betamethasone 0.1%w/v + Neomycin 0.5%w/v+ Chlorocresol 0.1% w/v"
* #"Ointment_Chloramphenicol_ophthalmic_0.01" "Ointment Chloramphenicol ophthalmic 0.01"
* #"Ointment_Chlorhexidine_(navi_malam)_0.04" "Ointment Chlorhexidine (navi malam) 0.04"
* #"Ointment_Ciprofloxacin_eye_oint_0.003" "Ointment Ciprofloxacin eye oint 0.003"
* #"Ointment_Clindamycin_0.01" "Ointment Clindamycin 0.01"
* #"Ointment_Cloben_G_" "Ointment Cloben-G"
* #"Ointment_Clobetasol__Gentamycin__Miconazole_" "Ointment Clobetasol +Gentamycin+ Miconazole"
* #"Ointment_Clobetasol_proprionate_0.0005" "Ointment Clobetasol proprionate 0.0005"
* #"Ointment_Clotrimazole_0.01" "Ointment Clotrimazole 0.01"
* #"Ointment_Clotrimazole_0.02" "Ointment Clotrimazole 0.02"
* #"Ointment_Fluconazole_" "Ointment Fluconazole"
* #"Ointment_Framycetin_5mg_ml" "Ointment Framycetin 5mg/ml"
* #"Ointment_Framycetin_Sulphate_5mg__Gramicidin_0.05m" "Ointment Framycetin Sulphate 5mg+ Gramicidin 0.05mg+Dexamethasone Sodium Metasulfobenzoate 0.5mg"
* #"Ointment_Fusidic_acid__Betamethasone_" "Ointment Fusidic acid+ Betamethasone"
* #"Ointment_Gentamycin_0.002" "Ointment Gentamycin 0.002"
* #"Ointment_Glyceryl_trinitrate_0.002" "Ointment Glyceryl trinitrate 0.002"
* #"Ointment_Halobetasol_propionate___Salicyclic_acid_" "Ointment Halobetasol propionate + Salicyclic acid 0.05%+3%"
* #"Ointment_Halobetasole_Gentamycin_" "Ointment Halobetasole Gentamycin"
* #"Ointment_Hydrocortisone_acetate__Fusidic_acid_1%_2" "Ointment Hydrocortisone acetate+ Fusidic acid 1%+2%"
* #"Ointment_Mupirocin_5gm" "Ointment Mupirocin 5gm"
* #"Ointment_Neomycine__Beclomethasone_" "Ointment Neomycine+ Beclomethasone"
* #"Ointment_Polysporin_" "Ointment Polysporin"
* #"Ointment_Silver_sulphadiazine_0.01" "Ointment Silver sulphadiazine 0.01"
* #"Ointment_Silver_sulphadiazine_0.002" "Ointment Silver sulphadiazine 0.002"
* #"Ointment_Tetracycline_eye_applicap_0.01" "Ointment Tetracycline eye applicap 0.01"
* #"Ointment_White_field_ointment_6%_3%" "Ointment White field ointment 6%+3%"
* #"Pessary_Clotrimazole_vaginal_pessary_100mg" "Pessary Clotrimazole vaginal pessary 100mg"
* #"Powder_Activated_Charcoal_10mg_sachet" "Powder Activated Charcoal 10mg/sachet"
* #"Powder_Ashwagandha_Churna_" "Powder Ashwagandha Churna"
* #"Powder_Balvita_1pkt" "Powder Balvita 1pkt"
* #"Solution_Beclomethasone_Inhaler_200mcg_dose" "Solution Beclomethasone Inhaler 200mcg/dose"
* #"Solution_Chlorhexidine_100ml" "Solution Chlorhexidine 100ml"
* #"Solution_Clobetasol_10gm" "Solution Clobetasol 10gm"
* #"Solution_Cyproheptadine_" "Solution Cyproheptadine"
* #"Solution_Deta2_expetorent_10ml" "Solution Deta2 expetorent 10ml"
* #"Solution_Disodium_Hydrogren_(Urine_alkalizer)_1.4g" "Solution Disodium Hydrogren (Urine alkalizer) 1.4gm"
* #"Solution_DNS_Dextrose_Normal_saline_0.9%_5%" "Solution DNS-Dextrose Normal saline 0.9%+5%"
* #"Solution_Medroxyprogesterone_150mg_mlin1mlvial" "Solution Medroxyprogesterone 150mg/mlin1mlvial"
* #"Solution_Normal_saline_0.009" "Solution Normal saline 0.009"
* #"Solution_NS__Normal_saline_0.009" "Solution NS- Normal saline 0.009"
* #"Solution_Ofloxacin_e_e_drop_0.003" "Solution Ofloxacin e/e drop 0.003"
* #"Solution_ORS_" "Solution ORS"
* #"Solution_Otosoft_2_3drop" "Solution Otosoft 2-3drop"
* #"Solution_Oxygen_inhalation_Medicinalgas" "Solution Oxygen inhalation Medicinalgas"
* #"Solution_Povidone_gargle_" "Solution Povidone gargle"
* #"Solution_Providine_0.1" "Solution Providine 0.1"
* #"Solution_RL_(Ringer&#x27;s_Lactate)_500ml" "Solution RL (Ringer's Lactate) 500ml"
* #"Solution_RUTF_2Pkt" "Solution RUTF 2Pkt"
* #"Spray_Beclomethasone_Nasal_Spray_" "Spray Beclomethasone Nasal Spray"
* #"Spray_Nasivion_5ml" "Spray Nasivion 5ml"
* #"Suppository_Bisacodyl_5mg" "Suppository Bisacodyl 5mg"
* #"Suppository_Bisacodyl_10mg" "Suppository Bisacodyl 10mg"
* #"Suppository_Glycerin_adult_" "Suppository Glycerin adult"
* #"Suppository_Glycerin_paed._" "Suppository Glycerin paed."
* #"Suspension_Antacid_(Aluminium_hydroxide___Magnesiu" "Suspension Antacid (Aluminium hydroxide + Magnesium hydroxide) 250mg+250mg"
* #"Suspension_Carbamazepine_100Mg_5ml" "Suspension Carbamazepine 100Mg/5ml"
* #"Suspension_Clotrimazole_mouth_paint_0.01" "Suspension Clotrimazole mouth paint 0.01"
* #"Suspension_Cough_expectorant_" "Suspension Cough expectorant"
* #"Suspension_Fluconazole_50mg_5ml" "Suspension Fluconazole 50mg/5ml"
* #"Syrup_Abhyarista_" "Syrup Abhyarista"
* #"Syrup_Albendazole_200mg_5ml" "Syrup Albendazole 200mg/5ml"
* #"Syrup_Alkalizer_5ml" "Syrup Alkalizer 5ml"
* #"Syrup_Allegra_30mg_5ml" "Syrup Allegra 30mg/5ml"
* #"Syrup_Amoxycillin_125mg_5ml" "Syrup Amoxycillin 125mg/5ml"
* #"Syrup_Amoxycillin_250mg_10ml" "Syrup Amoxycillin 250mg/10ml"
* #"Syrup_Amoxycillin__Clavulanic_acid_200mg_28.5mg" "Syrup Amoxycillin+ Clavulanic acid 200mg+28.5mg"
* #"Syrup_Amoxycillin_Cloxacillin_125mg_125mg" "Syrup Amoxycillin+Cloxacillin 125mg+125mg"
* #"Syrup_Ampicillin_Cloxacillin_125mg_125mg" "Syrup Ampicillin+Cloxacillin 125mg+125mg"
* #"Syrup_Anticold_125_1_2.5mg" "Syrup Anticold 125/1/2.5mg"
* #"Syrup_Antihistamine_5ml" "Syrup Antihistamine 5ml"
* #"Syrup_Arsil_dx_5ml" "Syrup Arsil dx 5ml"
* #"Syrup_Ashokarista_" "Syrup Ashokarista"
* #"Syrup_Azithromycin_100mg_5ml" "Syrup Azithromycin 100mg/5ml"
* #"Syrup_Azithromycin_200mg_5ml" "Syrup Azithromycin 200mg/5ml"
* #"Syrup_Beta__2_(Salbutamol)_2mg" "Syrup Beta -2 (Salbutamol) 2mg"
* #"Syrup_Beta__2_exp_" "Syrup Beta -2 exp"
* #"Syrup_Brica_BM_" "Syrup Brica BM"
* #"Syrup_Bromhexine_Hydrochloride_1.25mg_5ml" "Syrup Bromhexine Hydrochloride 1.25mg/5ml"
* #"Syrup_Bromhexine_Hydrochloride_4mg_5ml" "Syrup Bromhexine Hydrochloride 4mg/5ml"
* #"Syrup_Cefaclor_25mg_ml" "Syrup Cefaclor 25mg/ml"
* #"Syrup_Cefadroxil_125mg_5ml" "Syrup Cefadroxil 125mg/5ml"
* #"Syrup_Cefixime_25mg_ml" "Syrup Cefixime 25mg/ml"
* #"Syrup_Cefixime_50m_5ml" "Syrup Cefixime 50m/5ml"
* #"Syrup_Cefixime_200mg_5ml" "Syrup Cefixime 200mg/5ml"
* #"Syrup_Cefixime_and_Potassium_Clavulanate_50mg_31.2" "Syrup Cefixime and Potassium Clavulanate 50mg+31.25mg"
* #"Syrup_Cefpodoxime_50mg_5ml" "Syrup Cefpodoxime 50mg/5ml"
* #"Syrup_Cefpodoxime_Proxetil_DT_25mg_ml" "Syrup Cefpodoxime Proxetil DT 25mg/ml"
* #"Syrup_Cephalexin_100mg_ml" "Syrup Cephalexin 100mg/ml"
* #"Syrup_Cephalexin_125mg_5ml" "Syrup Cephalexin 125mg/5ml"
* #"Syrup_Cetirizine_HCL_(CTZ)_2.5mg" "Syrup Cetirizine HCL (CTZ) 2.5mg"
* #"Syrup_Cetirizine_HCL_(CTZ)_5mg_ml" "Syrup Cetirizine HCL (CTZ) 5mg/ml"
* #"Syrup_Cloxacillin_125mg_5ml" "Syrup Cloxacillin 125mg/5ml"
* #"Syrup_Cloxacillin_drop_125mg" "Syrup Cloxacillin drop 125mg"
* #"Syrup_Cotrimoxazole_240mg" "Syrup Cotrimoxazole 240mg"
* #"Syrup_Cremaffin_" "Syrup Cremaffin"
* #"Syrup_Dextromethorphan___Chlorpheniramine_maleate_" "Syrup Dextromethorphan + Chlorpheniramine maleate (10mg+2mg)/5ml"
* #"Syrup_Dextromethorphan_hydrobromide___Pheniramine_" "Syrup Dextromethorphan hydrobromide + Pheniramine maleate + Phenylephrine hydrochloride (7.5mg+7.5mg+2.5mg)/5ml"
* #"Syrup_Dicyclomine_10mg" "Syrup Dicyclomine 10mg"
* #"Syrup_Dicyclomine__Paracetamol__Cyclopam_10mg" "Syrup Dicyclomine+ Paracetamol- Cyclopam 10mg"
* #"Syrup_Dicyclomine__Simethicone_" "Syrup Dicyclomine+ Simethicone"
* #"Syrup_Digestive_enzyme_(Pepsin_Diatase)_10mg_50mg" "Syrup Digestive enzyme (Pepsin+Diatase) 10mg+50mg"
* #"Syrup_Disodium_hydrogen_citrate_(DJ_Citral)_1.40gm" "Syrup Disodium hydrogen citrate (DJ Citral) 1.40gm"
* #"Syrup_Domperidone_5mg" "Syrup Domperidone 5mg"
* #"Syrup_Erythromycin_125mg_5ml" "Syrup Erythromycin 125mg/5ml"
* #"Syrup_Fexofenadine_30mg_5ml" "Syrup Fexofenadine 30mg/5ml"
* #"Syrup_Flexon_125mg_5ml" "Syrup Flexon 125mg/5ml"
* #"Syrup_Flucloxacillin_125mg_5ml" "Syrup Flucloxacillin 125mg/5ml"
* #"Syrup_Folic_acid_0.1mcg_ml" "Syrup Folic acid 0.1mcg/ml"
* #"Syrup_Fortiplex_200ml" "Syrup Fortiplex 200ml"
* #"Syrup_Honitus_" "Syrup Honitus"
* #"Syrup_Ibuprofen_100mg_5ml" "Syrup Ibuprofen 100mg/5ml"
* #"Syrup_Ispasmodic_5ml" "Syrup Ispasmodic 5ml"
* #"Syrup_Kidcofe_5ml" "Syrup Kidcofe 5ml"
* #"Syrup_Lactulose_5ml" "Syrup Lactulose 5ml"
* #"Syrup_Liver_tonic_200ml" "Syrup Liver tonic 200ml"
* #"Syrup_Lomohist_" "Syrup Lomohist"
* #"Syrup_Lomohist_12mg" "Syrup Lomohist 12mg"
* #"Syrup_Metoclopramide_5mg_5ml" "Syrup Metoclopramide 5mg/5ml"
* #"Syrup_Metronidazole_200mg_5ml" "Syrup Metronidazole 200mg/5ml"
* #"Syrup_Metronidazole__diloxanide_furoate_200mg_250m" "Syrup Metronidazole+ diloxanide furoate 200mg+250mg"
* #"Syrup_Multivitamin_5ml" "Syrup Multivitamin 5ml"
* #"Syrup_Niko_125mg" "Syrup Niko 125mg"
* #"Syrup_ODT_(Ondansetron)_4mg_5ml" "Syrup ODT (Ondansetron) 4mg/5ml"
* #"Syrup_Ondansetron_5ml" "Syrup Ondansetron 5ml"
* #"Syrup_Paracetamol___Ibuprofen_(100mg_125mg)_5ml" "Syrup Paracetamol + Ibuprofen (100mg+125mg)/5ml"
* #"Syrup_Paracetamol___Ibuprofen_125_100mg" "Syrup Paracetamol + Ibuprofen 125+100mg"
* #"Syrup_Paracetamol___Phenylephrine_HCl___Chlorpheni" "Syrup Paracetamol + Phenylephrine HCl + Chlorpheniramine 125mg+5mg+1mg"
* #"Syrup_Paracetamol_125mg_5ml" "Syrup Paracetamol 125mg/5ml"
* #"Syrup_Paracetamol_150mg_5ml" "Syrup Paracetamol 150mg/5ml"
* #"Syrup_Paracetamol_250mg_10ml" "Syrup Paracetamol 250mg/10ml"
* #"Syrup_Racid_250_250mg" "Syrup Racid 250+250mg"
* #"Syrup_Ranitidine_(Raniped)_75mg_5ml" "Syrup Ranitidine (Raniped) 75mg/5ml"
* #"Syrup_Renil_100ml" "Syrup Renil 100ml"
* #"Syrup_Risperidone_1mg_ml" "Syrup Risperidone 1mg/ml"
* #"Syrup_Risperidone_2mg_ml" "Syrup Risperidone 2mg/ml"
* #"Syrup_Salbutamol___Bromhexine_2mg_4mg" "Syrup Salbutamol + Bromhexine 2mg+4mg"
* #"Syrup_Salbutamol_2mg" "Syrup Salbutamol 2mg"
* #"Syrup_Salbutamol_4mg" "Syrup Salbutamol 4mg"
* #"Syrup_Soothex_BM_" "Syrup Soothex BM"
* #"Syrup_Sucrafil_(Sucralfate)_500mg_5ml" "Syrup Sucrafil (Sucralfate) 500mg/5ml"
* #"Syrup_Terbutaline_Sulphate__Bromhexine_5ml" "Syrup Terbutaline Sulphate+ Bromhexine 5ml"
* #"Syrup_TUS_Q_Dx_" "Syrup TUS-Q Dx"
* #"Syrup_TUS_Q_Dx_(Dextromethorphan,_Chlorpheniramine" "Syrup TUS-Q Dx (Dextromethorphan, Chlorpheniramine maleate, Phenylephrine hcl) 7.5mg+5mg+1.5mg"
* #"Syrup_Tusq_dx_" "Syrup Tusq-dx"
* #"Syrup_Tussional_" "Syrup Tussional"
* #"Syrup_Vasodryl_(dextromethorphan_hbr_and_chlorphen" "Syrup Vasodryl (dextromethorphan hbr and chlorpheniramine maleate ) 10mg+2mg"
* #"Syrup_Vasodryl_3ml" "Syrup Vasodryl 3ml"
* #"Syrup_Vasodryl_8.5mg" "Syrup Vasodryl 8.5mg"
* #"Syrup_Vitamin_B_complex_5ml" "Syrup Vitamin B-complex 5ml"
* #"Tablet_2HRZE_4HR_1Tab" "Tablet 2HRZE+4HR 1Tab"
* #"Tablet_2HRZE_7HRE_" "Tablet 2HRZE+7HRE"
* #"Tablet_6HRZE_" "Tablet 6HRZE"
* #"Tablet_6HRZE_Lfx_" "Tablet 6HRZE+Lfx"
* #"Tablet_Acarbose_25mg" "Tablet Acarbose 25mg"
* #"Tablet_Acarbose_50mg" "Tablet Acarbose 50mg"
* #"Tablet_Aceclofenac_100mg" "Tablet Aceclofenac 100mg"
* #"Tablet_Aceclofenac_200mg" "Tablet Aceclofenac 200mg"
* #"Tablet_Acetazolamide_250mg" "Tablet Acetazolamide 250mg"
* #"Tablet_Acetazolamide_500mg" "Tablet Acetazolamide 500mg"
* #"Tablet_Acetylcystein_600mg" "Tablet Acetylcystein 600mg"
* #"Tablet_Aciloc_150mg" "Tablet Aciloc 150mg"
* #"Tablet_Acyclovir_100mg" "Tablet Acyclovir 100mg"
* #"Tablet_Acyclovir_200mg" "Tablet Acyclovir 200mg"
* #"Tablet_Acyclovir_800mg" "Tablet Acyclovir 800mg"
* #"Tablet_Acyclovir_DT_800mg" "Tablet Acyclovir DT 800mg"
* #"Tablet_Albendazole_200mg" "Tablet Albendazole 200mg"
* #"Tablet_Albendazole_400mg" "Tablet Albendazole 400mg"
* #"Tablet_Alendronate_70mg" "Tablet Alendronate 70mg"
* #"Tablet_Alfuzosin_10mg" "Tablet Alfuzosin 10mg"
* #"Tablet_Alfuzosin_10mg_10mg" "Tablet Alfuzosin 10mg 10mg"
* #"Tablet_Allopurinol_100mg" "Tablet Allopurinol 100mg"
* #"Tablet_Allopurinol_300mg" "Tablet Allopurinol 300mg"
* #"Tablet_Alprazolam_0.5mg" "Tablet Alprazolam 0.5mg"
* #"Tablet_Alprazolam_0.25mg" "Tablet Alprazolam 0.25mg"
* #"Tablet_Amiodarone_100mg" "Tablet Amiodarone 100mg"
* #"Tablet_Amiodarone_200mg" "Tablet Amiodarone 200mg"
* #"Tablet_Amisulpride_100mg" "Tablet Amisulpride 100mg"
* #"Tablet_Amisulpride_200mg" "Tablet Amisulpride 200mg"
* #"Tablet_Amisulpride_300mg" "Tablet Amisulpride 300mg"
* #"Tablet_Amitriptyline_(Traid)_25mg" "Tablet Amitriptyline (Traid) 25mg"
* #"Tablet_Amitriptyline_(Traid)_50mg" "Tablet Amitriptyline (Traid) 50mg"
* #"Tablet_Amitriptyline_(Traid)_75mg" "Tablet Amitriptyline (Traid) 75mg"
* #"Tablet_Amitriptyline_10mg" "Tablet Amitriptyline 10mg"
* #"Tablet_Amlod_L_(Amlodipine__Losartan)_5mg_50mg" "Tablet Amlod L (Amlodipine+ Losartan) 5mg+50mg"
* #"Tablet_Amlodipine_0.5mg" "Tablet Amlodipine 0.5mg"
* #"Tablet_Amlodipine_2.5mg" "Tablet Amlodipine 2.5mg"
* #"Tablet_Amlodipine_5mg" "Tablet Amlodipine 5mg"
* #"Tablet_Amlodipine_10mg" "Tablet Amlodipine 10mg"
* #"Tablet_Amlodipine_Besilate__Atenolol_2.5mg_25mg" "Tablet Amlodipine Besilate+ Atenolol 2.5mg+25mg"
* #"Tablet_Amlodipine_Besilate__Atenolol_2.5mg_50mg" "Tablet Amlodipine Besilate+ Atenolol 2.5mg+50mg"
* #"Tablet_Amlodipine_Besilate__Atenolol_5mg_25mg" "Tablet Amlodipine Besilate+ Atenolol 5mg+25mg"
* #"Tablet_Amlodipine_Besilate__Atenolol_5mg_50mg" "Tablet Amlodipine Besilate+ Atenolol 5mg+50mg"
* #"Tablet_Amlodipine_Besilate__Losartan_2.5mg_25mg" "Tablet Amlodipine Besilate+ Losartan 2.5mg+25mg"
* #"Tablet_Amlodipine_Besilate__Losartan_5mg_25mg" "Tablet Amlodipine Besilate+ Losartan 5mg+25mg"
* #"Tablet_Amlodipine__Atenelol_5mg_50mg" "Tablet Amlodipine+ Atenelol 5mg+50mg"
* #"Tablet_Amoxycillin_125mg" "Tablet Amoxycillin 125mg"
* #"Tablet_Amoxycillin_250mg" "Tablet Amoxycillin 250mg"
* #"Tablet_Amoxycillin_500mg" "Tablet Amoxycillin 500mg"
* #"Tablet_Amoxycillin__Clavulanic_acid_500mg_125mg" "Tablet Amoxycillin+ Clavulanic acid 500mg+125mg"
* #"Tablet_Amoxycillin__Clavulanic_acid_625Mg" "Tablet Amoxycillin+ Clavulanic acid 625Mg"
* #"Tablet_Ampicillin_500mg" "Tablet Ampicillin 500mg"
* #"Tablet_Anastrazole_1mg" "Tablet Anastrazole 1mg"
* #"Tablet_Antacid_(Aluminium_hydroxide___Magnesium_hy" "Tablet Antacid (Aluminium hydroxide + Magnesium hydroxide) 250mg+250mg"
* #"Tablet_Anticold_500mg" "Tablet Anticold 500mg"
* #"Tablet_Aripiprazole_10mg" "Tablet Aripiprazole 10mg"
* #"Tablet_Aripiprazole_15mg" "Tablet Aripiprazole 15mg"
* #"Tablet_Artemether___Lumefantrine_(ACT)_20MG_120MG" "Tablet Artemether + Lumefantrine (ACT) 20MG+120MG"
* #"Tablet_Aspirin_75mg" "Tablet Aspirin 75mg"
* #"Tablet_Aspirin_150mg" "Tablet Aspirin 150mg"
* #"Tablet_Aspirin_300mg" "Tablet Aspirin 300mg"
* #"Tablet_Asthalin_inhaler_200Mcg" "Tablet Asthalin inhaler 200Mcg"
* #"Tablet_Asthalin_Rotacap_(Salbutamol)_200mcg" "Tablet Asthalin Rotacap (Salbutamol) 200mcg"
* #"Tablet_Atenolol_50mg" "Tablet Atenolol 50mg"
* #"Tablet_Atenolol__Chlorthalidone_50mg_12.5mg" "Tablet Atenolol+ Chlorthalidone 50mg+12.5mg"
* #"Tablet_Atenolol__Chlorthalidone_50mg_25mg" "Tablet Atenolol+ Chlorthalidone 50mg+25mg"
* #"Tablet_Atorvastatin_5mg" "Tablet Atorvastatin 5mg"
* #"Tablet_Atorvastatin_10mg" "Tablet Atorvastatin 10mg"
* #"Tablet_Atorvastatin_20mg" "Tablet Atorvastatin 20mg"
* #"Tablet_Atrovastatin_40mg" "Tablet Atrovastatin 40mg"
* #"Tablet_Azithromycin_1gm" "Tablet Azithromycin 1gm"
* #"Tablet_Azithromycin_250mg" "Tablet Azithromycin 250mg"
* #"Tablet_Azithromycin_500mg" "Tablet Azithromycin 500mg"
* #"Tablet_Baclofen_10mg" "Tablet Baclofen 10mg"
* #"Tablet_Baclofen_25mg" "Tablet Baclofen 25mg"
* #"Tablet_Bisacodyl_gastro_resistant_5MG" "Tablet Bisacodyl gastro-resistant 5MG"
* #"Tablet_Buscopan_10mg" "Tablet Buscopan 10mg"
* #"Tablet_Calcium_500Mg" "Tablet Calcium 500Mg"
* #"Tablet_Calcium_and_vitamin_d3_500mg_250IU" "Tablet Calcium and vitamin d3 500mg+250IU"
* #"Tablet_Carbamazepine_100mg" "Tablet Carbamazepine 100mg"
* #"Tablet_Carbamazepine_200mg" "Tablet Carbamazepine 200mg"
* #"Tablet_Cefadroxil_500mg" "Tablet Cefadroxil 500mg"
* #"Tablet_Cefadroxil_monohydrate_250mg" "Tablet Cefadroxil monohydrate 250mg"
* #"Tablet_Cefadroxil_monohydrate_500mg" "Tablet Cefadroxil monohydrate 500mg"
* #"Tablet_Cefixime_100mg" "Tablet Cefixime 100mg"
* #"Tablet_Cefixime_200mg" "Tablet Cefixime 200mg"
* #"Tablet_Cefixime_400mg" "Tablet Cefixime 400mg"
* #"Tablet_Cefixime_and_Potassium_Clavulanate_200mg_12" "Tablet Cefixime and Potassium Clavulanate 200mg+125mg"
* #"Tablet_Cefpodoxime___Potassium_clavulanate_200mg_1" "Tablet Cefpodoxime + Potassium clavulanate 200mg+125mg"
* #"Tablet_Cefpodoxime_200mg" "Tablet Cefpodoxime 200mg"
* #"Tablet_Cefpodoxime_Proxetil_DT_200mg" "Tablet Cefpodoxime Proxetil DT 200mg"
* #"Tablet_Cefuroxime_Axetil_250mg" "Tablet Cefuroxime Axetil 250mg"
* #"Tablet_Cefuroxime_Axetil_500mg" "Tablet Cefuroxime Axetil 500mg"
* #"Tablet_Cetirizine_HCL_(CTZ)_5mg" "Tablet Cetirizine HCL (CTZ) 5mg"
* #"Tablet_Cetirizine_HCL_(CTZ)_10mg" "Tablet Cetirizine HCL (CTZ) 10mg"
* #"Tablet_Cetirizine_HCL_(CTZ)_20mg" "Tablet Cetirizine HCL (CTZ) 20mg"
* #"Tablet_Chlora_2mg" "Tablet Chlora 2mg"
* #"Tablet_Chloroquine_(cq)_150mg" "Tablet Chloroquine (cq) 150mg"
* #"Tablet_Chlorpheniramine_(CPM)_2mg" "Tablet Chlorpheniramine (CPM) 2mg"
* #"Tablet_Chlorpheniramine_(CPM)_3mg" "Tablet Chlorpheniramine (CPM) 3mg"
* #"Tablet_Chlorpheniramine_(CPM)_4mg" "Tablet Chlorpheniramine (CPM) 4mg"
* #"Tablet_Chlozoxazone___PCM_250mg_500mg" "Tablet Chlozoxazone + PCM 250mg+500mg"
* #"Tablet_Cholecalciferol_60000IU" "Tablet Cholecalciferol 60000IU"
* #"Tablet_Cinnarizine_(_Vertigon)_25mg" "Tablet Cinnarizine ( Vertigon) 25mg"
* #"Tablet_Cinnarizine_25mg" "Tablet Cinnarizine 25mg"
* #"Tablet_Ciprofloxacin_250mg" "Tablet Ciprofloxacin 250mg"
* #"Tablet_Ciprofloxacin_500mg" "Tablet Ciprofloxacin 500mg"
* #"Tablet_Clarithromycin_250" "Tablet Clarithromycin 250"
* #"Tablet_Clarithromycin_500mg" "Tablet Clarithromycin 500mg"
* #"Tablet_Clindamycin_150mg" "Tablet Clindamycin 150mg"
* #"Tablet_Clobazam_5mg" "Tablet Clobazam 5mg"
* #"Tablet_Clobazam_10mg" "Tablet Clobazam 10mg"
* #"Tablet_Clonazepam_0.5mg" "Tablet Clonazepam 0.5mg"
* #"Tablet_Clonazepam_0.25mg" "Tablet Clonazepam 0.25mg"
* #"Tablet_Clopidogrel_75mg" "Tablet Clopidogrel 75mg"
* #"Tablet_Codeine_15mg" "Tablet Codeine 15mg"
* #"Tablet_Combined_OCP_" "Tablet Combined OCP"
* #"Tablet_Corbamazire_(Carbamazepine)_200mg" "Tablet Corbamazire (Carbamazepine) 200mg"
* #"Tablet_Cotrimoxazole_240mg" "Tablet Cotrimoxazole 240mg"
* #"Tablet_Cotrimoxazole_480mg" "Tablet Cotrimoxazole 480mg"
* #"Tablet_Cotrimoxazole_960mg" "Tablet Cotrimoxazole 960mg"
* #"Tablet_Decold_500mg" "Tablet Decold 500mg"
* #"Tablet_Deepan_(Paracetamol_Diclofenac)_725mg" "Tablet Deepan (Paracetamol+Diclofenac) 725mg"
* #"Tablet_Dexamethasone_0.5mg" "Tablet Dexamethasone 0.5mg"
* #"Tablet_Diazepam_2mg" "Tablet Diazepam 2mg"
* #"Tablet_Diazepam_5mg" "Tablet Diazepam 5mg"
* #"Tablet_Diclofenac_50mg" "Tablet Diclofenac 50mg"
* #"Tablet_Diclofenac_75mg" "Tablet Diclofenac 75mg"
* #"Tablet_Diclofenac_100mg" "Tablet Diclofenac 100mg"
* #"Tablet_Dicyclomine_20mg" "Tablet Dicyclomine 20mg"
* #"Tablet_Dicyclomine__Mefenamic_acid_10mg_250mg" "Tablet Dicyclomine+ Mefenamic acid 10mg+250mg"
* #"Tablet_Digoxin_0.25Mg" "Tablet Digoxin 0.25Mg"
* #"Tablet_Digoxin_0.125mg" "Tablet Digoxin 0.125mg"
* #"Tablet_Domperidone_10mg" "Tablet Domperidone 10mg"
* #"Tablet_Drotaverine_40mg" "Tablet Drotaverine 40mg"
* #"Tablet_Drotaverine_80mg" "Tablet Drotaverine 80mg"
* #"Tablet_Duloxetine_20mg" "Tablet Duloxetine 20mg"
* #"Tablet_Duloxetine_30mg" "Tablet Duloxetine 30mg"
* #"Tablet_Ebastine_10mg" "Tablet Ebastine 10mg"
* #"Tablet_Ebastine_20mg" "Tablet Ebastine 20mg"
* #"Tablet_Ecox_90mg" "Tablet Ecox 90mg"
* #"Tablet_Efavirenz_200mg" "Tablet Efavirenz 200mg"
* #"Tablet_Efavirenz_600mg" "Tablet Efavirenz 600mg"
* #"Tablet_Emidon_5mg" "Tablet Emidon 5mg"
* #"Tablet_Enalapril_2.5Mg" "Tablet Enalapril 2.5Mg"
* #"Tablet_Enalpril_5mg" "Tablet Enalpril 5mg"
* #"Tablet_Enalpril_10mg" "Tablet Enalpril 10mg"
* #"Tablet_Ergometrine_0.5mg" "Tablet Ergometrine 0.5mg"
* #"Tablet_Erythromycin_250mg" "Tablet Erythromycin 250mg"
* #"Tablet_Erythromycin_500mg" "Tablet Erythromycin 500mg"
* #"Tablet_Escitalopram_5mg" "Tablet Escitalopram 5mg"
* #"Tablet_Esmoprazole_20mg" "Tablet Esmoprazole 20mg"
* #"Tablet_Esmoprazole_40mg" "Tablet Esmoprazole 40mg"
* #"Tablet_Esmoprazole__Sod._Bicarbonate_40mg" "Tablet Esmoprazole+ Sod. Bicarbonate 40mg"
* #"Tablet_Eterocoxibe_90mg" "Tablet Eterocoxibe 90mg"
* #"Tablet_Etoricoxib_90MG" "Tablet Etoricoxib 90MG"
* #"Tablet_Febuxostat_40mg" "Tablet Febuxostat 40mg"
* #"Tablet_Febuxostat_80mg" "Tablet Febuxostat 80mg"
* #"Tablet_Fenofibrate_160mg" "Tablet Fenofibrate 160mg"
* #"Tablet_Fenofibrate_200mg" "Tablet Fenofibrate 200mg"
* #"Tablet_Ferrous_ascorbate_Folic_acid_100mg_1.5mg" "Tablet Ferrous ascorbate+Folic acid 100mg+1.5mg"
* #"Tablet_Ferrous_Fumarate__Folic_acid_100mg_1mg" "Tablet Ferrous Fumarate+ Folic acid 100mg+1mg"
* #"Tablet_Ferrous_sulphate__folic_acid_(IFA)_60Mgand0" "Tablet Ferrous sulphate +folic acid (IFA) 60Mgand0.4mg"
* #"Tablet_Ferrous_sulphate__folic_acid_(IFA)_200mg_0." "Tablet Ferrous sulphate +folic acid (IFA) 200mg+0.4mg"
* #"Tablet_Ferrous_sulphate_60mg" "Tablet Ferrous sulphate 60mg"
* #"Tablet_Fexofenadine_60mg" "Tablet Fexofenadine 60mg"
* #"Tablet_Fexofenadine_120mg" "Tablet Fexofenadine 120mg"
* #"Tablet_Fexofenadine_180mg" "Tablet Fexofenadine 180mg"
* #"Tablet_Finasteride_1mg" "Tablet Finasteride 1mg"
* #"Tablet_Finasteride_5mg" "Tablet Finasteride 5mg"
* #"Tablet_Flavoxate_Hcl_200mg" "Tablet Flavoxate Hcl 200mg"
* #"Tablet_Flexon_400mg_375" "Tablet Flexon 400mg/375"
* #"Tablet_Flunarizine_5mg" "Tablet Flunarizine 5mg"
* #"Tablet_Flunarizine_10mg" "Tablet Flunarizine 10mg"
* #"Tablet_Fluoxetine_10mg" "Tablet Fluoxetine 10mg"
* #"Tablet_Fluoxetine_20mg" "Tablet Fluoxetine 20mg"
* #"Tablet_Flurbiprofen_100mg" "Tablet Flurbiprofen 100mg"
* #"Tablet_Flurbiprofen_200mg" "Tablet Flurbiprofen 200mg"
* #"Tablet_Folic_acid_5mg" "Tablet Folic acid 5mg"
* #"Tablet_Frusemid&amp;amiloride_40_5" "Tablet Frusemid&amiloride 40+5"
* #"Tablet_Frusemide_20mg" "Tablet Frusemide 20mg"
* #"Tablet_Frusemide_40mg" "Tablet Frusemide 40mg"
* #"Tablet_Frusemide20mg___Spironolactone_50mg_" "Tablet Frusemide20mg + Spironolactone 50mg"
* #"Tablet_Gabapentin_100mg" "Tablet Gabapentin 100mg"
* #"Tablet_Gabapentin_300mg" "Tablet Gabapentin 300mg"
* #"Tablet_Glimipride_0.5mg" "Tablet Glimipride 0.5mg"
* #"Tablet_Glimipride_1mg" "Tablet Glimipride 1mg"
* #"Tablet_Glimipride_2mg" "Tablet Glimipride 2mg"
* #"Tablet_Glimipride_3mg" "Tablet Glimipride 3mg"
* #"Tablet_Glimipride_4mg" "Tablet Glimipride 4mg"
* #"Tablet_Glucosamine_500mg" "Tablet Glucosamine 500mg"
* #"Tablet_Griseofulvin_125mg" "Tablet Griseofulvin 125mg"
* #"Tablet_Griseofulvin_250mg" "Tablet Griseofulvin 250mg"
* #"Tablet_Griseofulvin_500mg" "Tablet Griseofulvin 500mg"
* #"Tablet_Haloperidol_0.25mg" "Tablet Haloperidol 0.25mg"
* #"Tablet_Haloperidol_1.5_mg__Trihexyphenidyl_2mg_" "Tablet Haloperidol 1.5 mg +Trihexyphenidyl 2mg"
* #"Tablet_Haloperidol_1.5mg" "Tablet Haloperidol 1.5mg"
* #"Tablet_Haloperidol_5_mg__Trihexyphenidyl_2mg_" "Tablet Haloperidol 5 mg +Trihexyphenidyl 2mg"
* #"Tablet_Haloperidol_5mg" "Tablet Haloperidol 5mg"
* #"Tablet_hydrochlorothiazide_12.5mg" "Tablet hydrochlorothiazide 12.5mg"
* #"Tablet_Hydrochlorthiazide_12.5mg" "Tablet Hydrochlorthiazide 12.5mg"
* #"Tablet_Hydrochlorthiazide_25mg" "Tablet Hydrochlorthiazide 25mg"
* #"Tablet_Hydrochlothiazide_25mg" "Tablet Hydrochlothiazide 25mg"
* #"Tablet_Hydroxychloroquine_Sulfate_200mg" "Tablet Hydroxychloroquine Sulfate 200mg"
* #"Tablet_Hyoscine_butylbromide_10mg" "Tablet Hyoscine butylbromide 10mg"
* #"Tablet_Hyoscine_butylbromide_20mg" "Tablet Hyoscine butylbromide 20mg"
* #"Tablet_Ibuprofen_200mg" "Tablet Ibuprofen 200mg"
* #"Tablet_Ibuprofen_400mg" "Tablet Ibuprofen 400mg"
* #"Tablet_IFA_400_60mg" "Tablet IFA 400+60mg"
* #"Tablet_Indomethacine_50mg" "Tablet Indomethacine 50mg"
* #"Tablet_Indomethacine_SR_75mg" "Tablet Indomethacine SR 75mg"
* #"Tablet_Itraconazole_100mg" "Tablet Itraconazole 100mg"
* #"Tablet_Ketoralac_tromethamine_10mg" "Tablet Ketoralac tromethamine 10mg"
* #"Tablet_Klozeep_0.5mg" "Tablet Klozeep 0.5mg"
* #"Tablet_Labetalol_100mg" "Tablet Labetalol 100mg"
* #"Tablet_Labetalol_200mg" "Tablet Labetalol 200mg"
* #"Tablet_Levocetirizine_5mg" "Tablet Levocetirizine 5mg"
* #"Tablet_Levonorgesterol_75mg" "Tablet Levonorgesterol 75mg"
* #"Tablet_livetiracetam_500mg" "Tablet livetiracetam 500mg"
* #"Tablet_locasamide_50mg" "Tablet locasamide 50mg"
* #"Tablet_lorazepine_2mg" "Tablet lorazepine 2mg"
* #"Tablet_Lore_1MG" "Tablet Lore 1MG"
* #"Tablet_Losartan___hydrochlorothiazide_50mg_12.5mg" "Tablet Losartan + hydrochlorothiazide 50mg+12.5mg"
* #"Tablet_Losartan_25mg" "Tablet Losartan 25mg"
* #"Tablet_Losartan_50mg" "Tablet Losartan 50mg"
* #"Tablet_lucast_plus_10mg" "Tablet lucast plus 10mg"
* #"Tablet_MDT_combi_pack_MBADULT" "Tablet MDT combi pack MBADULT"
* #"Tablet_MDT_combi_pack_MBChild" "Tablet MDT combi pack MBChild"
* #"Tablet_Mefenamic_acid_500mg" "Tablet Mefenamic acid 500mg"
* #"Tablet_meftal_500mg" "Tablet meftal 500mg"
* #"Tablet_Metformin_500mg" "Tablet Metformin 500mg"
* #"Tablet_Metformin_850mg" "Tablet Metformin 850mg"
* #"Tablet_Metformin_1000mg" "Tablet Metformin 1000mg"
* #"Tablet_Metformin_G1_500mg_1mg" "Tablet Metformin G1 500mg+1mg"
* #"Tablet_Metformin_G1_1000mg_1mg" "Tablet Metformin G1 1000mg/1mg"
* #"Tablet_Metformin_G2_500mg_2mg" "Tablet Metformin G2 500mg+2mg"
* #"Tablet_Metformin_SR_500mg" "Tablet Metformin SR 500mg"
* #"Tablet_Metformin__Sitagliptin_1000mg_50mg" "Tablet Metformin+ Sitagliptin 1000mg+50mg"
* #"Tablet_Metformin_Linagliptin_1gm_2.5mg" "Tablet Metformin+Linagliptin 1gm+2.5mg"
* #"Tablet_Methylcobalamin_1500mcg" "Tablet Methylcobalamin 1500mcg"
* #"Tablet_Methyldopa_250Mg" "Tablet Methyldopa 250Mg"
* #"Tablet_Metoclopramide_5mg" "Tablet Metoclopramide 5mg"
* #"Tablet_Metoclopramide_10mg" "Tablet Metoclopramide 10mg"
* #"Tablet_Metoprolol_12.5Mg" "Tablet Metoprolol 12.5Mg"
* #"Tablet_Metronidazole_200mg" "Tablet Metronidazole 200mg"
* #"Tablet_Metronidazole_400mg" "Tablet Metronidazole 400mg"
* #"Tablet_Metronidazole__diloxanide_furoate_400mg_500" "Tablet Metronidazole+ diloxanide furoate 400mg+500mg"
* #"Tablet_Mifepristone___Misoprostol_200mg_4(200)mcg" "Tablet Mifepristone + Misoprostol 200mg+4(200)mcg"
* #"Tablet_Mifepristone___Misoprostol_200Mgand200mg" "Tablet Mifepristone + Misoprostol 200Mgand200mg"
* #"Tablet_Misoprostal_200mcg" "Tablet Misoprostal 200mcg"
* #"Tablet_Misoprostol_200Mcg" "Tablet Misoprostol 200Mcg"
* #"Tablet_Montelukast_10mg" "Tablet Montelukast 10mg"
* #"Tablet_mylod_l_5mg_50mg" "Tablet mylod l 5mg+50mg"
* #"Tablet_Mylod_L_Amlodipine5mg_Losartanpotassium50mg" "Tablet Mylod L Amlodipine5mg+Losartanpotassium50mg"
* #"Tablet_Myoside_(_Thiocolchicoside)_4mg" "Tablet Myoside ( Thiocolchicoside) 4mg"
* #"Tablet_Naproxen_500MG" "Tablet Naproxen 500MG"
* #"Tablet_Nefidipine_5mg" "Tablet Nefidipine 5mg"
* #"Tablet_Neproxyn_500mg" "Tablet Neproxyn 500mg"
* #"Tablet_Neurocal_113mg_15mcg" "Tablet Neurocal 113mg+15mcg"
* #"Tablet_Nifedipine_5mg" "Tablet Nifedipine 5mg"
* #"Tablet_Nifedipine_10mg" "Tablet Nifedipine 10mg"
* #"Tablet_Nitro_f_100mg" "Tablet Nitro-f 100mg"
* #"Tablet_Nitrofurantoin_100mg" "Tablet Nitrofurantoin 100mg"
* #"Tablet_ODT_(Ondansetron)_4mg" "Tablet ODT (Ondansetron) 4mg"
* #"Tablet_ODT_(Ondansetron)_10mg" "Tablet ODT (Ondansetron) 10mg"
* #"Tablet_Ofloxacin_400mg" "Tablet Ofloxacin 400mg"
* #"Tablet_Ollmisarten_20mg" "Tablet Ollmisarten 20mg"
* #"Tablet_Ornidazole_500mg" "Tablet Ornidazole 500mg"
* #"Tablet_Osart_20mg" "Tablet Osart 20mg"
* #"Tablet_Pantoprazole_40mg" "Tablet Pantoprazole 40mg"
* #"Tablet_Paracetamol___Chlorxoxazone_500mg_250mg" "Tablet Paracetamol + Chlorxoxazone 500mg+250mg"
* #"Tablet_Paracetamol___Codeine_500_10mg" "Tablet Paracetamol + Codeine 500+10mg"
* #"Tablet_Paracetamol___Ibuprofen_325mg_400mg" "Tablet Paracetamol + Ibuprofen 325mg+400mg"
* #"Tablet_Paracetamol___Ibuprofen_500_400mg" "Tablet Paracetamol + Ibuprofen 500+400mg"
* #"Tablet_Paracetamol___Phenylephrine_HCl___Chlorphen" "Tablet Paracetamol + Phenylephrine HCl + Chlorpheniramine 500mg+10mg+4mg"
* #"Tablet_Paracetamol_250mg" "Tablet Paracetamol 250mg"
* #"Tablet_Paracetamol_500mg" "Tablet Paracetamol 500mg"
* #"Tablet_PCM_500mg" "Tablet PCM 500mg"
* #"Tablet_Penicillin_250MG" "Tablet Penicillin 250MG"
* #"Tablet_Perinorm_(Metoclopramide)_10mg" "Tablet Perinorm (Metoclopramide) 10mg"
* #"Tablet_Pheniramine__Phenylephrine_5_15mg" "Tablet Pheniramine+ Phenylephrine 5+15mg"
* #"Tablet_Phenobarbitone_30Mg" "Tablet Phenobarbitone 30Mg"
* #"Tablet_Phenobarbitone_60mg" "Tablet Phenobarbitone 60mg"
* #"Tablet_Pills_(OCP)_" "Tablet Pills (OCP)"
* #"Tablet_Prazopress_5mg" "Tablet Prazopress 5mg"
* #"Tablet_Prednisolone_5mg" "Tablet Prednisolone 5mg"
* #"Tablet_Prednisolone_10mg" "Tablet Prednisolone 10mg"
* #"Tablet_Prednisolone_20mg" "Tablet Prednisolone 20mg"
* #"Tablet_Prednisolone_40mg" "Tablet Prednisolone 40mg"
* #"Tablet_Primaquine_7.5MG" "Tablet Primaquine 7.5MG"
* #"Tablet_promethazine_10mg" "Tablet promethazine 10mg"
* #"Tablet_promethazine_25mg" "Tablet promethazine 25mg"
* #"Tablet_Propanolol_(Minil)_10mg" "Tablet Propanolol (Minil) 10mg"
* #"Tablet_Propanolol_(Minil)_20mg" "Tablet Propanolol (Minil) 20mg"
* #"Tablet_Propanolol_(Minil)_25mg" "Tablet Propanolol (Minil) 25mg"
* #"Tablet_Propanolol_20MG" "Tablet Propanolol 20MG"
* #"Tablet_Pyredoxine_10mg" "Tablet Pyredoxine 10mg"
* #"Tablet_Pyridoxine_10mg" "Tablet Pyridoxine 10mg"
* #"Tablet_Rabeprazole_20mg" "Tablet Rabeprazole 20mg"
* #"Tablet_Ranitidine_150mg" "Tablet Ranitidine 150mg"
* #"Tablet_Risperidone_0.5mg" "Tablet Risperidone 0.5mg"
* #"Tablet_Risperidone_1mg" "Tablet Risperidone 1mg"
* #"Tablet_Risperidone_2mg" "Tablet Risperidone 2mg"
* #"Tablet_Risperidone_3mg" "Tablet Risperidone 3mg"
* #"Tablet_Rosuvastatin_10mg" "Tablet Rosuvastatin 10mg"
* #"Tablet_Salbutamol_2mg" "Tablet Salbutamol 2mg"
* #"Tablet_Salbutamol_4mg" "Tablet Salbutamol 4mg"
* #"Tablet_Salbutamol_Nebulizer_(Asthalin)_100mcg" "Tablet Salbutamol Nebulizer (Asthalin) 100mcg"
* #"Tablet_Salbutamol_rotacaps_200mcg" "Tablet Salbutamol rotacaps 200mcg"
* #"Tablet_Serratiopeptidase_(Pepsa)_5MG" "Tablet Serratiopeptidase (Pepsa) 5MG"
* #"Tablet_Sertraline_25mg" "Tablet Sertraline 25mg"
* #"Tablet_Sinex_1TAB" "Tablet Sinex 1TAB"
* #"Tablet_Sitagliptin_50mg_50mg" "Tablet Sitagliptin 50mg 50mg"
* #"Tablet_Sodium_valporate_200mg" "Tablet Sodium valporate 200mg"
* #"Tablet_Sodium_valporate_300mg" "Tablet Sodium valporate 300mg"
* #"Tablet_Sodium_valporate_600mg" "Tablet Sodium valporate 600mg"
* #"Tablet_Sodium_valproate_400mg" "Tablet Sodium valproate 400mg"
* #"Tablet_Sodium_valproate_500mg" "Tablet Sodium valproate 500mg"
* #"Tablet_Spironolactone_25mg" "Tablet Spironolactone 25mg"
* #"Tablet_Telmisartan_80mg" "Tablet Telmisartan 80mg"
* #"Tablet_Terbinafine_250mg" "Tablet Terbinafine 250mg"
* #"Tablet_Thiamine_100mg" "Tablet Thiamine 100mg"
* #"Tablet_Thyronorm_25mg" "Tablet Thyronorm 25mg"
* #"Tablet_Thyronorm_75mcg" "Tablet Thyronorm 75mcg"
* #"Tablet_Tinidazole_1gm" "Tablet Tinidazole 1gm"
* #"Tablet_Tinidazole_2gm" "Tablet Tinidazole 2gm"
* #"Tablet_Tinidazole_250mg" "Tablet Tinidazole 250mg"
* #"Tablet_Tinidazole_500mg" "Tablet Tinidazole 500mg"
* #"Tablet_Tizanidine_2MG" "Tablet Tizanidine 2MG"
* #"Tablet_Traid_(Amitriptyline)_10mg" "Tablet Traid (Amitriptyline) 10mg"
* #"Tablet_Tranexamic_acid_500mg" "Tablet Tranexamic acid 500mg"
* #"Tablet_Tranexamic_acid_1000mg" "Tablet Tranexamic acid 1000mg"
* #"Tablet_Ultracid_250mg_250mg_250mg" "Tablet Ultracid 250mg+250mg+250mg"
* #"Tablet_Ursodeoxycholic_acid_150" "Tablet Ursodeoxycholic acid 150"
* #"Tablet_Valporic_acid_200mg" "Tablet Valporic acid 200mg"
* #"Tablet_Valproate_XR_500mg" "Tablet Valproate XR 500mg"
* #"Tablet_Vitamin_B_complex_1Tab" "Tablet Vitamin B-complex 1Tab"
* #"Tablet_Vitamin_C_80mg" "Tablet Vitamin C 80mg"
* #"Tablet_Voglibose_0.2mg" "Tablet Voglibose 0.2mg"
* #"Tablet_Voglibose_0.3mg" "Tablet Voglibose 0.3mg"
* #"Tablet_Zinc_sulphate_10mg" "Tablet Zinc sulphate 10mg"
* #"Tablet_Zinc_sulphate_20mg" "Tablet Zinc sulphate 20mg"
* #"Tablet_Zoxafen_forte_750mg" "Tablet Zoxafen forte 750mg"
* #"Tablet_Atrovastatin_5mg" "Tablet Atrovastatin 5mg"
* #"Tablet_Atrovastatin_10mg" "Tablet Atrovastatin 10mg"
* #"Tablet_Atrovastatin_20mg" "Tablet Atrovastatin 20mg"
