CodeSystem: SASFPMethodsAllContraceptivesMinilapNSVPillsDepoCondomCS
Title: "SAS-FP methods-all contraceptives-Minilap/NSV/Pills/Depo/Condom"
* #"1" "Minilap"
* #"2" "NSV"
* #"3" "Implant"
* #"4" "IUCD"
* #"5" "Depoprovera"
* #"6" "Pills Combined Oral"
* #"7" "Condom"
* #"8" "Other"
