Logical: 
Title: "खोप, पोषण र अन्य कार्यक्रम"
Parent: Base
* executionDate 0..1 date ""
* campaignHwMobilized 0..1 decimal "VME-EPI-campaign-HW mobilized"
* campaignImmunizedFemale 0..1 decimal "VME-EPI-campaign-immunized Female"
* campaignImmunizedMale 0..1 decimal "VME-EPI-campaign-immunized Male"
* campaignVmVialOtherExpended 0..1 decimal "VME-EPI-campaign-vaccineManagement-vial other expended"
* campaignVmVialOtherReturned 0..1 decimal "VME-EPI-campaign-vaccineManagement-vial other Returned"
* campaignVmVialReceived 0..1 decimal "VME-EPI-campaign-vaccineManagement-vial received"
* campaignVmVialUsedInImmunization 0..1 decimal "VME-EPI-campaign-vaccineManagement-vial used in immunization"
* scNumberOfEpiSessions 0..1 decimal "VME-EPI-SessionConducted-Number of EPI Sessions"
* scNumberOfHygieneSessions 0..1 decimal "VME-EPI-SessionConducted-Number of Hygiene Sessions"
* scNumberOfParticipantsInHygieneSession 0..1 decimal "VME-EPI-SessionConducted-Number of Participants in Hygiene Session"
* vmEpiExpenseVial 0..1 decimal "VME-EPI-VaccineManagement- EPI expense vial"
* vmOtherExpenseVial 0..1 decimal "VME-EPI-VaccineManagement- Other Expense vial"
* vmReceivedVial 0..1 decimal "VME-EPI-VaccineManagement-Received Vial"
* vmeEpiVaccinemanagementVaccinename 0..1 code "VME-EPI-VaccineManagement-VaccineName"
* vmeEpiVaccinemanagementVaccinename from TotalVaccineCollectionVS (required)
* vmVaccineVialReturn 0..1 decimal "VME-EPI-VaccineManagement- Vaccine vial return"
* healthpromotionNoOfParticipants 0..1 decimal "VME-Nutrition-healthPromotion-No. of Participants"
* healthpromotionNoOfSessions 0..1 decimal "VME-Nutrition-healthPromotion-No. of sessions"
* healthpromotionSeccionMonth 0..1 decimal "VME-Nutrition-healthPromotion-Seccion Month"
* healthpromotionSeccionPlace 0..1 decimal "VME-Nutrition-healthPromotion-Seccion Place"
* shnAlbendazole110ClassChildFemale 0..1 decimal "VME-Nutrition-SHN-albendazole 1-10 class child Female"
* shnAlbendazole110ClassChildMale 0..1 decimal "VME-Nutrition-SHN-albendazole 1-10 class child Male"
* shnIfa13CycleGiven 0..1 decimal "VME-Nutrition-SHN-IFA 13 cycle given"
* shnIfa26CycleGiven 0..1 decimal "VME-Nutrition-SHN-IFA 26 cycle given"
* vacNoAlbedazoleGiven1259Children 0..1 decimal "VME-Nutrition-Vitamin A Campaign- No. Albedazole given 12-59 children"
* vacNoAlbedazoleGivenChildFemale 0..1 decimal "VME-Nutrition-Vitamin A Campaign- No. Albedazole given child Female"
* vacNoVitAGiven1259Children 0..1 decimal "VME-Nutrition-Vitamin A Campaign- No. Vit A given 12-59 children"
* vacNoVitAGiven611Children 0..1 decimal "VME-Nutrition-Vitamin A Campaign- No. Vit A given 6-11 children"
* populationPeerEducationCounselledFemale 0..1 decimal "VME-Population-peer education-counselled female"
* populationPeerEducationCounselledMale 0..1 decimal "VME-Population-peer education-counselled male"
* populationPeerEducationFunctionalInfoCorners 0..1 decimal "VME-Population-peer education-functional Info. corners"
* populationPeerEducationIsSchoolReporting 0..1 decimal "VME-Population-peer education-no. of school reporting"
* populationPeerEducationSchoolSupervised 0..1 decimal "VME-Population-peer education-schools supervised"
* epiClinicConducted 0..1 decimal "VME-EPI Clinic-Conducted"
* epiClinicPlanned 0..1 decimal "VME-EPI Clinic-Planned"
* epiSessionsPlanned 0..1 decimal "VME-EPI Sessions-Planned"
* epiSessionsConducted 0..1 decimal "VME-EPI Sessions-Conducted"
* hygieneSessionsPlanned 0..1 decimal "VME-Hygiene Sessions-Planned"
* hygieneSessionsConducted 0..1 decimal "VME-Hygiene Sessions-Conducted"
* fchvReported 0..1 decimal "VME-FCHV-Reported"
* fchvNumber 0..1 decimal "VME-FCHV-Number"
* vaccineManagementBcgOpenVialInEpi 0..1 decimal "VME-Vaccine Management-BCG-Open vial in EPI"
* vaccineManagementBcgOtherExpendedVial 0..1 decimal "VME-Vaccine Management-BCG-Other Expended Vial"
* vaccineManagementBcgReceivedVial 0..1 decimal "VME-Vaccine Management-BCG-Received Vial"
* vaccineManagementBcgReturnedVial 0..1 decimal "VME-Vaccine Management-BCG-Returned Vial"
* vaccineManagementBopvOpenVialInEpi 0..1 decimal "VME-Vaccine Management-bOPV-Open vial in EPI"
* vaccineManagementBopvOtherExpendedVial 0..1 decimal "VME-Vaccine Management-bOPV-Other Expended Vial"
* vaccineManagementBopvReceivedVial 0..1 decimal "VME-Vaccine Management-bOPV-Received Vial"
* vaccineManagementBopvReturnedVial 0..1 decimal "VME-Vaccine Management-bOPV-Returned Vial"
* vaccineManagementDptOpenVialInEpi 0..1 decimal "VME-Vaccine Management-DPT-Open vial in EPI"
* vaccineManagementDptOtherExpendedVial 0..1 decimal "VME-Vaccine Management-DPT-Other Expended Vial"
* vaccineManagementDptReceivedVial 0..1 decimal "VME-Vaccine Management-DPT-Received Vial"
* vaccineManagementDptReturnedVial 0..1 decimal "VME-Vaccine Management-DPT-Returned Vial"
* vaccineManagementFipvOpenVialInEpi 0..1 decimal "VME-Vaccine Management-fIPV-Open vial in EPI"
* vaccineManagementFipvOtherExpendedVial 0..1 decimal "VME-Vaccine Management-fIPV-Other Expended Vial"
* vaccineManagementFipvReceivedVial 0..1 decimal "VME-Vaccine Management-fIPV-Received Vial"
* vaccineManagementFipvReturnedVial 0..1 decimal "VME-Vaccine Management-fIPV-Returned Vial"
* vaccineManagementHpvOpenVialInEpi 0..1 decimal "VME-Vaccine Management-HPV-Open vial in EPI"
* vaccineManagementHpvOtherExpendedVial 0..1 decimal "VME-Vaccine Management-HPV-Other Expended Vial"
* vaccineManagementHpvReceivedVial 0..1 decimal "VME-Vaccine Management-HPV-Received Vial"
* vaccineManagementHpvReturnedVial 0..1 decimal "VME-Vaccine Management-HPV-Returned Vial"
* vaccineManagementJeOpenVialInEpi 0..1 decimal "VME-Vaccine Management-JE-Open vial in EPI"
* vaccineManagementJeOtherExpendedVial 0..1 decimal "VME-Vaccine Management-JE-Other Expended Vial"
* vaccineManagementJeReceivedVial 0..1 decimal "VME-Vaccine Management-JE-Received Vial"
* vaccineManagementJeReturnedVial 0..1 decimal "VME-Vaccine Management-JE-Returned Vial"
* vaccineManagementMrOpenVialInEpi 0..1 decimal "VME-Vaccine Management-MR-Open vial in EPI"
* vaccineManagementMrOtherExpendedVial 0..1 decimal "VME-Vaccine Management-MR-Other Expended Vial"
* vaccineManagementMrReceivedVial 0..1 decimal "VME-Vaccine Management-MR-Received Vial"
* vaccineManagementMrReturnedVial 0..1 decimal "VME-Vaccine Management-MR-Returned Vial"
* vaccineManagementPcvOpenVialInEpi 0..1 decimal "VME-Vaccine Management-PCV-Open vial in EPI"
* vaccineManagementPcvOtherExpendedVial 0..1 decimal "VME-Vaccine Management-PCV-Other Expended Vial"
* vaccineManagementPcvReceivedVial 0..1 decimal "VME-Vaccine Management-PCV-Received Vial"
* vaccineManagementPcvReturnedVial 0..1 decimal "VME-Vaccine Management-PCV-Returned Vial"
* vaccineManagementRotaOpenVialInEpi 0..1 decimal "VME-Vaccine Management-Rota-Open vial in EPI"
* vaccineManagementRotaOtherExpendedVial 0..1 decimal "VME-Vaccine Management-Rota-Other Expended Vial"
* vaccineManagementRotaReceivedVial 0..1 decimal "VME-Vaccine Management-Rota-Received Vial"
* vaccineManagementRotaReturnedVial 0..1 decimal "VME-Vaccine Management-Rota-Returned Vial"
* vaccineManagementTcvOpenVialInEpi 0..1 decimal "VME-Vaccine Management-TCV-Open vial in EPI"
* vaccineManagementTcvOtherExpendedVial 0..1 decimal "VME-Vaccine Management-TCV-Other Expended Vial"
* vaccineManagementTcvReceivedVial 0..1 decimal "VME-Vaccine Management-TCV-Received Vial"
* vaccineManagementTcvReturnedVial 0..1 decimal "VME-Vaccine Management-TCV-Returned Vial"
* vaccineManagementTdOpenVialInEpi 0..1 decimal "VME-Vaccine Management-Td-Open vial in EPI"
* vaccineManagementTdOtherExpendedVial 0..1 decimal "VME-Vaccine Management-Td-Other Expended Vial"
* vaccineManagementTdReceivedVial 0..1 decimal "VME-Vaccine Management-Td-Received Vial"
* vaccineManagementTdReturnedVial 0..1 decimal "VME-Vaccine Management-Td-Returned Vial"
* hfInforamtionAdolescentFriendlyServiceSite 0..1 boolean "VME-HF Inforamtion-Adolescent friendly Service site"
* hfInforamtionArtSite 0..1 boolean "VME-HF Inforamtion-ART Site"
* hfInforamtionBeoncSite 0..1 boolean "VME-HF Inforamtion-BEONC Site"
* hfInforamtionBirthingCenter 0..1 boolean "VME-HF Inforamtion-Birthing center"
* hfInforamtionCbpmtctSite 0..1 boolean "VME-HF Inforamtion-CBPMTCT site"
* hfInforamtionCeoncSite 0..1 boolean "VME-HF Inforamtion-CEONC Site"
* hfInforamtionDotsSite 0..1 boolean "VME-HF Inforamtion-DOTS Site"
* hfInforamtionHtcSite 0..1 boolean "VME-HF Inforamtion-HTC site"
* hfInforamtionImplantServiceSite 0..1 boolean "VME-HF Inforamtion-Implant Service site"
* hfInforamtionIucdServiceSite 0..1 boolean "VME-HF Inforamtion-IUCD service site"
* hfInforamtionLaboratorySite 0..1 boolean "VME-HF Inforamtion-Laboratory Site"
* hfInforamtionMicroscopySite 0..1 boolean "VME-HF Inforamtion-Microscopy Site"
* hfInforamtionOtcSite 0..1 boolean "VME-HF Inforamtion-OTC site"
* hfInforamtionOtherSpecify 0..1 boolean "VME-HF Inforamtion-Other Specify"
* hfInforamtionPmtctSite 0..1 boolean "VME-HF Inforamtion-PMTCT site"
* hfInforamtionSasSite 0..1 boolean "VME-HF Inforamtion-SAS site"
* serviceAvaibilityGeneralEmergencyService 0..1 boolean "VME-Service Avaibility-General emergency service"
* serviceAvaibilityGeriatric 0..1 boolean "VME-Service Avaibility-Geriatric"
* serviceAvaibilityImci 0..1 boolean "VME-Service Avaibility-IMCI"
* serviceAvaibilityImmunizationService 0..1 boolean "VME-Service Avaibility-Immunization Service"
* serviceAvaibilityInfectiousDis 0..1 boolean "VME-Service Avaibility-Infectious dis"
* serviceAvaibilityMaternalHealth 0..1 boolean "VME-Service Avaibility-Maternal health"
* serviceAvaibilityMentalHealth 0..1 boolean "VME-Service Avaibility-Mental Health"
* serviceAvaibilityNcd 0..1 boolean "VME-Service Avaibility-NCD"
* serviceAvaibilityNutritionServices 0..1 boolean "VME-Service Avaibility-Nutrition Services"
* serviceAvaibilityPromotionalHealthServices 0..1 boolean "VME-Service Avaibility-Promotional Health Services"
* serviceAvaibilityRhService 0..1 boolean "VME-Service Avaibility-RH service"
* nutritionIfaAdolescent13Weeks 0..1 decimal "VME-Nutrition-IFA Adolescent 13 weeks-School"
* nutritionIfaAdolescent26Weeks 0..1 decimal "VME-Nutrition-IFA Adolescent 26 weeks-school"
* heSessionCommunityParticipants 0..1 decimal "VME-HE Session-Community participants"
* heSessionCommunitySession 0..1 decimal "VME-HE Session-Community session"
* heSessionOtherParticipants 0..1 decimal "VME-HE Session-Other participants"
* heSessionOtherSession 0..1 decimal "VME-HE Session-Other session"
* heSessionSchoolParticipants 0..1 decimal "VME-HE Session-School participants"
* heSessionSchoolSession 0..1 decimal "VME-HE Session-School session"
* peerEducation 0..1 decimal "VME-Peer Education"
* phcOrcConducted 0..1 decimal "VME-PHC/ORC-Conducted"
* phcOrcPlanned 0..1 decimal "VME-PHC/ORC-Planned"
* vmeGeneralReportingDate 0..1 date "VME-General-Reporting Date"
