Logical: FCHV
Title: "FCHV"
Parent: Base
* executionDate 0..1 date ""
* mcAnc1stAncCheckEnsured 0..1 decimal "VME-FCHV-Monthlycumulative-ANC1st ANC check ensured"
* mcAncheGiven 0..1 decimal "VME-FCHV-Monthlycumulative-ANCHE given"
* mcAncironRedistribution 0..1 decimal "VME-FCHV-Monthlycumulative-ANCIron redistribution"
* mcAncmisoprostolGivenEnsured 0..1 decimal "VME-FCHV-Monthlycumulative-ANCMisoprostol given ensured"
* mcAncpregnantWomenReferred 0..1 decimal "VME-FCHV-Monthlycumulative-ANCPregnant women referred"
* mcAncpregnantWomenReferredForPmtct 0..1 decimal "VME-FCHV-Monthlycumulative-ANCPregnant women referred for PMTCT"
* mcAncpregnantWomenVisited 0..1 decimal "VME-FCHV-Monthlycumulative-ANCpregnant women visited"
* mcAncreferredForInstitutionalDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-ANCReferred for institutional delivery"
* mcCrvsbithRegistrationEnsured 0..1 decimal "VME-FCHV-Monthlycumulative-CRVSBith registration ensured"
* mcCrvsdeathRegistrationEnsured 0..1 decimal "VME-FCHV-Monthlycumulative-CRVSDeath registration ensured"
* mcCrvstimelyBirthRegistrationCouselled 0..1 decimal "VME-FCHV-Monthlycumulative-CRVStimely birth registration couselled"
* mcCrvstimelyDeathRegistraitionEnsured 0..1 decimal "VME-FCHV-Monthlycumulative-CRVStimely death registraition ensured"
* mcFpcondomPeopleCount 0..1 decimal "VME-FCHV-Monthlycumulative-FPCondom people count"
* mcFpcondomPieceDistributed 0..1 decimal "VME-FCHV-Monthlycumulative-FPCondom piece distributed"
* mcFpcouplesReferredForFp 0..1 decimal "VME-FCHV-Monthlycumulative-FPCouples referred for FP"
* mcFpecDose 0..1 decimal "VME-FCHV-Monthlycumulative-FPEC dose"
* mcFpecWomen 0..1 decimal "VME-FCHV-Monthlycumulative-FPEC women"
* mcFpheFp 0..1 decimal "VME-FCHV-Monthlycumulative-FPHE FP"
* mcFppillDistributionWomen 0..1 decimal "VME-FCHV-Monthlycumulative-FPPill distribution women"
* mcFppillsCycleDistributed 0..1 decimal "VME-FCHV-Monthlycumulative-FPPills cycle distributed"
* mcHeheChildHealth 0..1 decimal "VME-FCHV-Monthlycumulative-HEHE child health"
* mcHeheHealthLifeStyleNumber 0..1 decimal "VME-FCHV-Monthlycumulative-HEHE Health life style number"
* mcHeheHealthLifeStyleTimes 0..1 decimal "VME-FCHV-Monthlycumulative-HEHE Health life style times"
* mcHomebirthensuredNoBath24Hour 0..1 decimal "VME-FCHV-Monthlycumulative-HomebirthEnsured no bath 24 hour"
* mcHomebirthliveBirthAtHome 0..1 decimal "VME-FCHV-Monthlycumulative-HomebirthLive birth at home"
* mcHomebirthstillBirthAtHome 0..1 decimal "VME-FCHV-Monthlycumulative-HomebirthStill birth at home"
* mcImamkwashiworkerReferred 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMKwashiworker Referred"
* mcImammuacGreen 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMMUAC Green"
* mcImammuacRedReferred 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMMUAC Red Referred"
* mcImammuacYellow 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMMUAC Yellow"
* mcImamredCured 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMred cured"
* mcImamredDefaulter 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMRed defaulter"
* mcImamredNotImproved 0..1 decimal "VME-FCHV-Monthlycumulative-IMAMred not improved"
* mcImcia2ari259mCases 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2ARI 2-59M cases"
* mcImcia2ariHomeTreatmentCouseling 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2ARI home treatment couseling"
* mcImcia2ariReferred259m 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2ARI referred 2-59M"
* mcImcia2diarrhoea259mCases 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Diarrhoea 2-59M cases"
* mcImcia2infantDeath1259m 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Infant death 12-59M"
* mcImcia2infantDeath211m 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Infant death 2-11M"
* mcImcia2orsPacketsDistributedG5 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2ORS packets distributed G5"
* mcImcia2orsPacketsDistributedU5 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2ORS packets distributed U5"
* mcImcia2postneonatalDeathCommunity 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Postneonatal death community"
* mcImcia2sickChildReferred259m 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Sick child referred 2-59M"
* mcImcia2treatedWithOrsAndZinc 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Treated with ORS and Zinc"
* mcImcia2zincDistributed 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIA2Zinc Distributed"
* mcImcib2neonatalDeath07 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2Neonatal death0-7"
* mcImcib2neonatalDeath0828 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2Neonatal death0-8-28"
* mcImcib2neonatalDeath2959 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2Neonatal death29-59"
* mcImcib2sickChild07d 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2sick child 0-7D"
* mcImcib2sickChild2959d 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2Sick child 29-59D"
* mcImcib2sickChild828d 0..1 decimal "VME-FCHV-Monthlycumulative-IMCIB2Sick child 8-28D"
* mcImmunizationchildFullyImmunized 0..1 decimal "VME-FCHV-Monthlycumulative-ImmunizationChild fully immunized"
* mcImmunizationnewChildReferredForEpi 0..1 decimal "VME-FCHV-Monthlycumulative-ImmunizationNew child referred for EPI"
* mcImmunizationparticipationEpiClinic 0..1 decimal "VME-FCHV-Monthlycumulative-ImmunizationParticipation EPI clinic"
* mcImmunizationparticipationPhcorc 0..1 decimal "VME-FCHV-Monthlycumulative-ImmunizationParticipation PHCORC"
* mcIycfbaalvita1217First 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 12-17 first"
* mcIycfbaalvita1217Second 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 12-17 Second"
* mcIycfbaalvita1823First 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 18-23 first"
* mcIycfbaalvita1823Second 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 18-23 second"
* mcIycfbaalvita1823Third 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 18-23 third"
* mcIycfbaalvita611First 0..1 decimal "VME-FCHV-Monthlycumulative-IYCFBaalvita 6-11 first"
* mcMnchchxCordEnsuredHomeDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHCHX cord ensured home delivery"
* mcMnchcouselingIycf 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHCouseling IYCF"
* mcMnchebfEnsuredHomeDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHEBF ensured home delivery"
* mcMnchhomeDeliveryAsphyxiaManagement 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHHome delivery asphyxia management"
* mcMnchifaForPostpartumMother 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHIFA for postpartum mother"
* mcMnchinvolvedDuringDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHInvolved during delivery"
* mcMnchkmcEnsuredHomeDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHKMC ensured home delivery"
* mcMnchliveBirthByHw 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHLive birth by HW"
* mcMnchliveBirthFacility 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHLive birth facility"
* mcMnchliveBirthHome 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHLive birth home"
* mcMnchlowWeightNewborn 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHLow weight newborn"
* mcMnchmaternalDeathDuringDeliveryCommunity 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHMaternal death during delivery community"
* mcMnchmaternalDeathDuringPostpartumCommunity 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHMaternal death during postpartum community"
* mcMnchmaternalDeathDuringPregnancyCommunity 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHMaternal death during pregnancy community"
* mcMnchnormalWieghtNewborn 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHNormal wieght Newborn"
* mcMnchnotBathed24HourHomeDelivery 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHNot bathed 24 hour home delivery"
* mcMnchphcThirdDayVisit 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHPHC third day visit"
* mcMnchpnc29DayVisit 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHPNC 29 day visit"
* mcMnchpncSeventhDayVisit 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHPNC seventh day visit"
* mcMnchreferredPncCheck 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHReferred PNC check"
* mcMnchveryLowWeightNewborn 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHVery low weight newborn"
* mcMnchvitAForPostpartumMother 0..1 decimal "VME-FCHV-Monthlycumulative-MNCHVit A for postpartum mother"
* mcNcdmentalHealthReferred 0..1 decimal "VME-FCHV-Monthlycumulative-NCDMental health referred"
* mcNcdndcCasesReferred 0..1 decimal "VME-FCHV-Monthlycumulative-NCDNDC cases referred"
* mcNutritionadolescentIfa13Weeks 0..1 decimal "VME-FCHV-Monthlycumulative-NutritionAdolescent IFA 13 weeks"
* mcNutritionadolescentIfa26Weeks 0..1 decimal "VME-FCHV-Monthlycumulative-NutritionAdolescent IFA 26 weeks"
* mcOthermghMeetingNumber 0..1 decimal "VME-FCHV-Monthlycumulative-OtherMGH meeting number"
* mcOthermgmHwParticiapted 0..1 decimal "VME-FCHV-Monthlycumulative-OtherMGM HW particiapted"
* mcOthermgmParticipants 0..1 decimal "VME-FCHV-Monthlycumulative-OtherMGM participants"
* mcOthertotalAmountAtRevolvingFund 0..1 decimal "VME-FCHV-Monthlycumulative-OtherTotal amount at revolving fund"
* mcReferralelderlyReferred 0..1 decimal "VME-FCHV-Monthlycumulative-ReferralElderly referred"
* mcReferralfirstAidNumber 0..1 decimal "VME-FCHV-Monthlycumulative-Referralfirst aid number"
* mcReferralreferredAhs 0..1 decimal "VME-FCHV-Monthlycumulative-ReferralReferred AHS"
* mcReferralreferredFirstAid 0..1 decimal "VME-FCHV-Monthlycumulative-ReferralReferred First AID"
* mcReferralreferredForSas 0..1 decimal "VME-FCHV-Monthlycumulative-ReferralReferred for SAS"
* mcReferralreferredProlongedCough 0..1 decimal "VME-FCHV-Monthlycumulative-ReferralReferred prolonged cough"
* mcRhmorbiditycervicalCancerScreeningReferred 0..1 decimal "VME-FCHV-Monthlycumulative-RHMorbidityCervical cancer screening referred"
* mcRhmorbidityuterusProlapseReferred 0..1 decimal "VME-FCHV-Monthlycumulative-RHMorbidityUterus prolapse referred"
* mcTbreferredPossibleLeprosy 0..1 decimal "VME-FCHV-Monthlycumulative-TBReferred possible Leprosy"
* mcTbreferredPossibleTb 0..1 decimal "VME-FCHV-Monthlycumulative-TBReferred possible TB"
* fchvMcTotalClientServed 0..1 decimal "VME-FCHV-Monthlycumulative-Total Client Served"
