Logical: LabTestRequestResult
Title: "Lab Test Request/Result"
Parent: Base
* executionDate 0..1 date ""
* bacteriologyBodyFluidAfb 0..1 string "LS - Bacteriology-Body fluid AFB"
* bacteriologyCultureBlood 0..1 string "LS - Bacteriology-Culture-Blood"
* bacteriologyCultureBodyFluid 0..1 string "LS - Bacteriology-Culture-Body Fluid"
* bacteriologyCultureCsf 0..1 string "LS - Bacteriology-Culture-CSF"
* bacteriologyCultureEnt 0..1 string "LS - Bacteriology-Culture-ENT"
* bacteriologyCultureOthers 0..1 string "LS - Bacteriology-Culture-Others"
* bacteriologyCulturePus 0..1 string "LS - Bacteriology-Culture-Pus"
* bacteriologyCultureSputum 0..1 string "LS - Bacteriology-Culture-Sputum"
* bacteriologyCultureStool 0..1 string "LS - Bacteriology-Culture-Stool"
* bacteriologyCultureSwab 0..1 string "LS - Bacteriology-Culture-Swab"
* bacteriologyCultureUrine 0..1 string "LS - Bacteriology-Culture-Urine"
* bacteriologyCultureWater 0..1 string "LS - Bacteriology-Culture-Water"
* bacteriologyFungusCulture 0..1 string "LS - Bacteriology-Fungus-Culture"
* bacteriologyFungusKoh 0..1 string "LS - Bacteriology-Fungus KOH"
* bacteriologyGmStain 0..1 string "LS - Bacteriology-Gm stain"
* bacteriologyIndiaInk 0..1 string "LS - Bacteriology-India Ink"
* bacteriologyLeprosySmear 0..1 string "LS - Bacteriology-Leprosy smear"
* bacteriologyOtherAfb 0..1 string "LS - Bacteriology-Other AFB"
* bacteriologyOthers 0..1 string "LS - Bacteriology-others"
* bacteriologySputumAfbTotal 0..1 string "LS - Bacteriology-Sputum AFB-total"
* bacteriologyWidal 0..1 string "LS - Bacteriology-Widal"
* biochemistry24hrProtine 0..1 string "LS - Biochemistry-24hr protine"
* biochemistry24hrUrineUA 0..1 string "LS - Biochemistry-24hr urine U/A"
* biochemistryAlbumin 0..1 string "LS - Biochemistry-Albumin"
* biochemistryAlkPhos 0..1 string "LS - Biochemistry-Alk Phos"
* biochemistryAmylase 0..1 string "LS - Biochemistry-Amylase"
* biochemistryAso 0..1 string "LS - Biochemistry-ASO"
* biochemistryBiliD 0..1 string "LS - Biochemistry-Bili-D"
* biochemistryBilirubinTest 0..1 string "LS - Biochemistry- Bilirubin test"
* biochemistryBiliT 0..1 string "LS - Biochemistry-Bili-T"
* biochemistryBloodUrea 0..1 string "LS - Biochemistry-Blood urea"
* biochemistryCalcium 0..1 string "LS - Biochemistry-Calcium"
* biochemistryCpkMb 0..1 string "LS - Biochemistry-CPK-MB"
* biochemistryCpkNac 0..1 string "LS - Biochemistry-CPK-NAC"
* biochemistryCreatinine 0..1 string "LS - Biochemistry-Creatinine"
* biochemistryCreatinineClearance 0..1 string "LS - Biochemistry-Creatinine Clearance"
* biochemistryCrProtein 0..1 string "LS - Biochemistry-CR protein"
* biochemistryGammaGt 0..1 string "LS - Biochemistry-Gamma GT"
* biochemistryHdl 0..1 string "LS - Biochemistry-HDL"
* biochemistryIronProfileTestConducted 0..1 string "LS - Biochemistry- Iron Profile test Conducted"
* biochemistryIsoTropI 0..1 string "LS - Biochemistry-Iso-Trop-I"
* biochemistryLdh 0..1 string "LS - Biochemistry-LDH"
* biochemistryLdl 0..1 string "LS - Biochemistry-LDL"
* biochemistryMagnesiumTest 0..1 string "LS - Biochemistry- Magnesium test"
* biochemistryMicroAlbumin 0..1 string "LS - Biochemistry-Micro albumin"
* biochemistryOthers 0..1 string "LS - Biochemistry-Others"
* biochemistryPhosPhorus 0..1 string "LS - Biochemistry-Phos-phorus"
* biochemistryPotassiumK 0..1 string "LS - Biochemistry-Potassium-K"
* biochemistryProtein 0..1 string "LS - Biochemistry-Protein"
* biochemistryRaFactor 0..1 string "LS - Biochemistry-RA factor"
* biochemistrySgot 0..1 string "LS - Biochemistry-SGOT"
* biochemistrySgpt 0..1 string "LS - Biochemistry-SGPT"
* biochemistrySodiumNa 0..1 string "LS - Biochemistry-Sodium-Na"
* biochemistrySugarF 0..1 string "LS - Biochemistry-Sugar-F"
* biochemistryTg 0..1 string "LS - Biochemistry-TG"
* biochemistryTibcTest 0..1 string "LS - Biochemistry- TIBC test"
* biochemistryTotalCholes 0..1 string "LS - Biochemistry-Total choles"
* biochemistryUricAcid 0..1 string "LS - Biochemistry-Uric acid"
* drugAnalysisCarbaMazepine 0..1 string "LS - Drug Analysis-Carba-mazepine"
* drugAnalysisCyclosporine 0..1 string "LS - Drug Analysis-Cyclosporine"
* drugAnalysisDigoXine 0..1 string "LS - Drug Analysis-Digo-xine"
* drugAnalysisOthers 0..1 string "LS - Drug Analysis-Others"
* drugAnalysisPhenyToin 0..1 string "LS - Drug Analysis-Pheny-toin"
* drugAnalysisTacroLimus 0..1 string "LS - Drug Analysis-Tacro-limus"
* drugAnalysisValporicAcid 0..1 string "LS - Drug Analysis-Valporic acid"
* haematologyAefTest 0..1 string "LS - Haematology- AEF test"
* haematologyAlcTest 0..1 string "LS - Haematology- ALC test"
* haematologyAldeHydeTest 0..1 string "LS - Haematology- Alde-hyde test"
* haematologyApttTest 0..1 string "LS - Haematology- APTT test"
* haematologyBloddGroupTest 0..1 string "LS - Haematology- Blodd Group test"
* haematologyBoneMarrowAnalysis 0..1 string "LS - Haematology- Bone Marrow Analysis"
* haematologyBtTest 0..1 string "LS - Haematology- BT test"
* haematologyCoombsTest 0..1 string "LS - Haematology- Coombs test"
* haematologyCrossMatchingConducted 0..1 string "LS - Haematology- Cross Matching Conducted"
* haematologyCtTest 0..1 string "LS - Haematology- CT test"
* haematologyDDimerTest 0..1 string "LS - Haematology- D-dimer test"
* haematologyDlcBandsTest 0..1 string "LS - Haematology- DLC  Bands test"
* haematologyDlcBasoTest 0..1 string "LS - Haematology- DLC  Baso test"
* haematologyDlcEosinoTest 0..1 string "LS - Haematology- DLC  Eosino test"
* haematologyDlcLymphoTest 0..1 string "LS - Haematology- DLC  Lympho test"
* haematologyDlcMonoTest 0..1 string "LS - Haematology- DLC  Mono test"
* haematologyDlcNeutroTest 0..1 string "LS - Haematology- DLC  Neutro test"
* haematologyDlcOthersTest 0..1 string "LS - Haematology- DLC  Others test"
* haematologyDlcTestConducted 0..1 string "LS - Haematology- DLC test Conducted"
* haematologyEsrTest 0..1 string "LS - Haematology- ESR test"
* haematologyFacIxTest 0..1 string "LS - Haematology- Fac IX test"
* haematologyFacViiiTest 0..1 string "LS - Haematology- Fac VIII test"
* haematologyFdpTest 0..1 string "LS - Haematology- FDP test"
* haematologyHba1cTest 0..1 string "LS - Haematology- HbA1c test"
* haematologyHbElectroPhoresisTest 0..1 string "LS - Haematology- Hb Electro-phoresis test"
* haematologyLdBodiesTest 0..1 string "LS - Haematology- LD Bodies test"
* haematologyLeTest 0..1 string "LS - Haematology- LE test"
* haematologyMchcTest 0..1 string "LS - Haematology- MCHC test"
* haematologyMchTest 0..1 string "LS - Haematology- MCH test"
* haematologyMcvTest 0..1 string "LS - Haematology- MCV test"
* haematologyMfPosTest 0..1 string "LS - Haematology- MF Pos. test"
* haematologyMfTotalTest 0..1 string "LS - Haematology- MF Total test"
* haematologyMpTest 0..1 string "LS - Haematology- MP  test"
* haematologyOtherTest 0..1 string "LS - Haematology- Other test"
* haematologyPbsTestConducted 0..1 string "LS - Haematology- PBS test Conducted"
* haematologyPfTestConducted 0..1 string "LS - Haematology- PF test Conducted"
* haematologyPMixTest 0..1 string "LS - Haematology- P-MIX test"
* haematologyPtInrTest 0..1 string "LS - Haematology- PT-INR test"
* haematologyPvTest 0..1 string "LS - Haematology- PV test"
* haematologyRdwTestConducted 0..1 string "LS - Haematology- RDW test Conducted"
* haematologyReticTest 0..1 string "LS - Haematology- Retic test"
* haematologySicklingTestConducted 0..1 string "LS - Haematology- Sickling Test Conducted"
* haematologySpecialStainMpoTestConducted 0..1 string "LS - Haematology- Special Stain- MPO test Conducted"
* haematologySpecialStainPasTestConducted 0..1 string "LS - Haematology- Special Stain- PAS test Conducted"
* haematologyTlcHbTest 0..1 string "LS - Haematology- TLC-  Hb test"
* haematologyTlcPlatletsTest 0..1 string "LS - Haematology- TLC-  Platlets test"
* haematologyTlcRbcTest 0..1 string "LS - Haematology- TLC-  RBC test"
* haematologyTlcWbcTest 0..1 string "LS - Haematology- TLC-  WBC test"
* haematologyUrineForHemosiderinTestConducted 0..1 string "LS - Haematology- Urine for Hemosiderin test Conducted"
* histopathologyCytologyBiopsyHE 0..1 string "LS - Histopathology/Cytology-Biopsy  H&E"
* histopathologyCytologyBiopsyOther 0..1 string "LS - Histopathology/Cytology-Biopsy Other"
* histopathologyCytologyCytologyGiemsa 0..1 string "LS - Histopathology/Cytology Cytology-Giemsa"
* histopathologyCytologyCytologyOthers 0..1 string "LS - Histopathology/Cytology Cytology-Others"
* histopathologyCytologyCytologyPap 0..1 string "LS - Histopathology/Cytology Cytology-Pap"
* hormonesEndocrinologyAFetoProt 0..1 string "LS - Hormones/Endocrinology-a feto prot."
* hormonesEndocrinologyCortisol 0..1 string "LS - Hormones/Endocrinology-Cortisol"
* hormonesEndocrinologyFsh 0..1 string "LS - Hormones/Endocrinology-FSH"
* hormonesEndocrinologyLh 0..1 string "LS - Hormones/Endocrinology-LH"
* hormonesEndocrinologyOestrogen 0..1 string "LS - Hormones/Endocrinology-Oestrogen"
* hormonesEndocrinologyOthers 0..1 string "LS - Hormones/Endocrinology-Others"
* hormonesEndocrinologyProgesterone 0..1 string "LS - Hormones/Endocrinology-Progesterone"
* hormonesEndocrinologyProLactine 0..1 string "LS - Hormones/Endocrinology-Pro-lactine"
* hormonesEndocrinologyT3 0..1 string "LS - Hormones/Endocrinology-T3"
* hormonesEndocrinologyT4 0..1 string "LS - Hormones/Endocrinology-T4"
* hormonesEndocrinologyTestosterone 0..1 string "LS - Hormones/Endocrinology-Testosterone"
* hormonesEndocrinologyTsh 0..1 string "LS - Hormones/Endocrinology-TSH"
* hormonesEndocrinologyVitB12TestConducted 0..1 string "LS - Hormones/Endocrinology-Vit.B12 test Conducted"
* hormonesEndocrinologyVitDTestConducted 0..1 string "LS - Hormones/Endocrinology-Vit.D test Conducted"
* immunoHistoChemistryCytoKeratin 0..1 string "LS - Immuno-Histo-Chemistry- Cyto-keratin"
* immunoHistoChemistryEr 0..1 string "LS - Immuno-Histo-Chemistry- ER"
* immunoHistoChemistryGFap 0..1 string "LS - Immuno-Histo-Chemistry- G-FAP"
* immunoHistoChemistryOthers 0..1 string "LS - Immuno-Histo-Chemistry- Others"
* immunoHistoChemistryPr 0..1 string "LS - Immuno-Histo-Chemistry- PR"
* immunoHistoChemistryS100 0..1 string "LS - Immuno-Histo-Chemistry- s-100"
* immunoHistoChemistryViMentin 0..1 string "LS - Immuno-Histo-Chemistry- Vi-mentin"
* immunologyAmoeBiasis 0..1 string "LS - Immunology-Amoe-biasis"
* immunologyAnaTest 0..1 string "LS - Immunology-ANA-test"
* immunologyAntiCcpTest 0..1 string "LS - Immunology- Anti CCP test"
* immunologyAntiDsdnaTest 0..1 string "LS - Immunology- Anti-dsDNA test"
* immunologyAntiTpoTest 0..1 string "LS - Immunology- Anti TPO test"
* immunologyBruCella 0..1 string "LS - Immunology-Bru-cella"
* immunologyCa125 0..1 string "LS - Immunology-CA-125"
* immunologyCa153 0..1 string "LS - Immunology-Ca 15.3"
* immunologyCa199 0..1 string "LS - Immunology-Ca 19-9"
* immunologyCea 0..1 string "LS - Immunology-CEA"
* immunologyChickungunyaTest 0..1 string "LS - Immunology- Chickungunya test"
* immunologyCmvTest 0..1 string "LS - Immunology- CMV test"
* immunologyCrp 0..1 string "LS - Immunology-CRP"
* immunologyCysticeRcosis 0..1 string "LS - Immunology-Cystice-rcosis"
* immunologyDengueVe 0..1 string "LS - Immunology-Dengue +ve"
* immunologyEchinoCoccus 0..1 string "LS - Immunology-Echino-coccus"
* immunologyFerriTine 0..1 string "LS - Immunology-Ferri-tine"
* immunologyHPyloriTest 0..1 string "LS - Immunology- H.Pylori test"
* immunologyHsvTest 0..1 string "LS - Immunology- HSV test"
* immunologyJeVe 0..1 string "LS - Immunology-JE +ve"
* immunologyLeptoSpira 0..1 string "LS - Immunology-Lepto-spira"
* immunologyMantoux 0..1 string "LS - Immunology-Mantoux"
* immunologyMeaslesIgG 0..1 string "LS - Immunology-MEASLES-IG-G"
* immunologyPragnacy 0..1 string "LS - Immunology-Pragnacy"
* immunologyProteinElectroPhoresis 0..1 string "LS - Immunology-Protein Electro-phoresis"
* immunologyPrp 0..1 string "LS - Immunology-PRP"
* immunologyPsa 0..1 string "LS - Immunology-PSA"
* immunologyRapidMpTotal 0..1 string "LS - Immunology-Rapid MP-total"
* immunologyRapidMpVePf 0..1 string "LS - Immunology-Rapid MP +ve PF"
* immunologyRapidMpVePv 0..1 string "LS - Immunology-Rapid MP +ve PV"
* immunologyRk39Total 0..1 string "LS - Immunology-RK-39-total"
* immunologyRprVdrlTotal 0..1 string "LS - Immunology-RPR-VDRL-total"
* immunologyRprVdrlVe 0..1 string "LS - Immunology-RPR-VDRL +ve"
* immunologyRubellaIgg 0..1 string "LS - Immunology-RUBELLA-IGG"
* immunologyScrubTyphusTest 0..1 string "LS - Immunology- Scrub Typhus test"
* immunologyThyroGlobulin 0..1 string "LS - Immunology-Thyro-globulin"
* immunologyToxoTest 0..1 string "LS - Immunology- Toxo test"
* immunologyTphaTest 0..1 string "LS - Immunology-TPHA-test"
* labBacteriologyAnaerobicCulture 0..1 string "LS - Lab-Bacteriology-Anaerobic Culture"
* labImmunologyPMixPositive 0..1 string "LS - Lab-Immunology- P.Mix positive"
* labMolecularCovid19Pcr 0..1 string "LS - Lab-Molecular-COVID19 PCR"
* labMolecularInfluenza 0..1 string "LS - Lab-Molecular-Influenza"
* labMolecularLeukemiaPanel 0..1 string "LS - Lab-Molecular-Leukemia Panel"
* labVirologyHavElisaCliaPositive 0..1 string "LS - Lab-Virology-HAV ELISA/CLIA Positive"
* labVirologyHavElisaCliaTests 0..1 string "LS - Lab-Virology-HAV ELISA/CLIA Tests"
* labVirologyHbsagElisaCliaPositive 0..1 string "LS - Lab-Virology-HBsAg ELISA/CLIA Positive"
* labVirologyHbsagElisaCliaTests 0..1 string "LS - Lab-Virology-HBsAg ELISA/CLIA Tests"
* labVirologyHcvElisaCliaPositive 0..1 string "LS - Lab-Virology-HCV ELISA/CLIA Positive"
* labVirologyHcvElisaCliaTests 0..1 string "LS - Lab-Virology-HCV ELISA/CLIA Tests"
* labVirologyHivElisaClia 0..1 string "LS - Lab-Virology-HIV ELISA/CLIA"
* labVirologyHivElisaCliaPositive 0..1 string "LS - Lab-Virology-HIV ELISA/CLIA Positive"
* parasitologyAceTone 0..1 string "LS - Parasitology- Ace-tone"
* parasitologyBenceJonesProt 0..1 string "LS - Parasitology- Bence-jones prot"
* parasitologyBilePigments 0..1 string "LS - Parasitology- Bile pigments"
* parasitologyBileSalts 0..1 string "LS - Parasitology- Bile salts"
* parasitologyChyle 0..1 string "LS - Parasitology- Chyle"
* parasitologyOccultBlood 0..1 string "LS - Parasitology- Occult blood"
* parasitologyOthers 0..1 string "LS - Parasitology- Others"
* parasitologyPorphoBilinogen 0..1 string "LS - Parasitology- Porpho-bilinogen"
* parasitologyReducingSugar 0..1 string "LS - Parasitology- Reducing sugar"
* parasitologySemenAnalysis 0..1 string "LS - Parasitology- Semen-analysis"
* parasitologySpGravity 0..1 string "LS - Parasitology- Sp. Gravity"
* parasitologyStoolRE 0..1 string "LS - Parasitology- Stool R/E"
* parasitologyUrineRE 0..1 string "LS - Parasitology- Urine R/E"
* parasitologyUrobiLinogen 0..1 string "LS - Parasitology- Urobi-linogen"
* virologyAntiHbcag 0..1 string "LS - Virology-Anti-HBcAg"
* virologyAntiHbe 0..1 string "LS - Virology-Anti-HBe"
* virologyAntiHbs 0..1 string "LS - Virology-Anti-HBs"
* virologyCd4Count 0..1 string "LS - Virology-CD4 count"
* virologyHbcag 0..1 string "LS - Virology-HBcAg"
* virologyHbeag 0..1 string "LS - Virology-HBeAg"
* virologyHbsagVe 0..1 string "LS - Virology-HBsAg +ve"
* virologyHcvVe 0..1 string "LS - Virology-HCV +ve"
* virologyHevVe 0..1 string "LS - Virology-HEV +ve"
* virologyHivVe 0..1 string "LS - Virology-HIV +ve"
* virologyOthers 0..1 string "LS - Virology-Others"
* virologyViralLoad 0..1 string "LS - Virology-Viral load"
* virologyWesternBlot 0..1 string "LS - Virology-Western blot"
